bugsnag/bugsnag-js-performance

- packages/core/lib/attributes.ts
- packages/core/lib/config.ts
- packages/core/lib/time.ts
- packages/core/lib/validation.ts
- packages/core/tests/attributes.test.ts
- packages/core/tests/config.test.ts
- packages/core/tests/time.test.ts
- packages/core/tests/validation.test.ts
To improve number validation by ensuring all used numbers are "real" numbers (not NaN, Infinity or -Infinity)
Added unit test to ensure span attributes are not added when not a valid number
> [PLAT-10201] Improve number validation

- packages/platforms/browser/lib/on-settle/index.ts
- packages/platforms/browser/tests/on-settle/index.test.ts
We now wait 100ms in case the settlers unsettle immediately after calling 'onSettle'
This ensures we aren't settling over-eagerly when the page is _about_ to change (or make network requests) but hasn't actually done so at the point 'onSettle' is called
For example, previously this would have settled immediately but now it will not as the DOM is mutated in the 100ms "cooldown period":
```ts
const span = BugsnagPerformance.startSpan('a')
onSettle(() => { span.end() })
document.body.innerHTML = ':)'
```
> Apply a 100ms cooldown period in onSettle

- packages/core/lib/span-context.ts
- packages/core/tests/span-context.test.ts
Updates the default `SpanContextStorage` implementation to accept a `BackgroundingListener` as a constructor arg - the storage class now listens for changes in background state and clears the context stack when the state changes.
`SpanContext`s are only pushed onto the context stack if the app is in the foreground.
> Clear `SpanContextStorage` when the app is backgrounded

- packages/core/lib/validation.ts
- packages/core/tests/validation.test.ts
- packages/platforms/browser/lib/config.ts
Small PR to add a new `isBoolean` validation function as we have a lot of boolean options in the browser configuration
> Add `isBoolean` validation function

- packages/platforms/browser/lib/delivery.ts
- packages/platforms/browser/tests/delivery.test.ts
Send the current time on the device when delivering traces using the `Bugsnag-Sent-At` header
> Add 'Bugsnag-Sent-At' header

- packages/platforms/browser/lib/auto-instrumentation/full-page-load-plugin.ts
- packages/platforms/browser/lib/auto-instrumentation/page-load-phase-spans.ts
- packages/platforms/browser/tests/auto-instrumentation/network-request-plugin.test.ts
- packages/platforms/browser/tests/auto-instrumentation/page-load-phase-spans.test.ts
- packages/platforms/browser/tests/auto-instrumentation/page-load-span-plugin.test.ts
- packages/platforms/browser/tests/auto-instrumentation/route-change-plugin.test.ts
- test/browser/features/page-load-spans.feature
- test/browser/features/steps/browser-steps.rb
Ensure all `PageLoadPhase` spans are direct children of the full page load span
> Make `PageLoadPhase` spans sub-spans of the full page load span

- packages/platforms/browser/lib/delivery.ts
- packages/platforms/browser/tests/delivery.test.ts
This reverts #228 as the issue has now been fixed in the pipeline
> Reinstate 'Bugsnag-Sent-At' header"

- bin/release.sh
Ensure version tag is pushed on release
> Ensure release tag is pushed to remote

- .github/ISSUE_TEMPLATE/A.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/support.md
Adding BugSnag JS Perf issue templates.
> [SUP-3154] Automated adjustment of repository templates

- bin/release.sh
- dockerfiles/Dockerfile.release
To ensure the automated release script installs packages correctly and does not attempt to publish private packages (test utils, etc)
> fix: :bug: update automated release script

- test/browser/features/server-responses.feature
Await sampling request before updating response headers
> Fix flakey test

- packages/platforms/browser/lib/auto-instrumentation/resource-load-plugin.ts
- packages/platforms/browser/tests/auto-instrumentation/resource-load-plugin.test.ts
Modify URLs or prevent delivery of spans in resource load spans
> [PLAT-10603] Implement networkRequestCallback in resource loads

- CHANGELOG.md
- packages/core/lib/batch-processor.ts
- packages/core/tests/delivery.test.ts
- packages/test-utilities/lib/create-span.ts
Ensure latest sampling value is used when creating a batch for delivery
> [PLAT-10670] Resampling broken in web

- test/browser/features/fixtures/packages/manual-span/index.html
- test/browser/features/fixtures/packages/manual-span/src/index.js
- test/browser/features/fixtures/packages/network-span-control/index.html
- test/browser/features/fixtures/packages/resource-load-spans/src/index.js
- test/browser/features/manual-spans.feature
Improve reliability of test fixture due to failures [like this](https://buildkite.com/bugsnag/bugsnag-js-performance/builds/1860#0189b438-f28d-4f79-a7db-696facd729a8) where the batch was too small to include the span we were asserting against
> Improve end to end test reliability

- CHANGELOG.md
- packages/platforms/react-native/lib/id-generator/id-generator.test.ts
- packages/platforms/react-native/lib/id-generator/id-generator.ts
To be able to generate span and trace ids in React Native
Added unit tests for 16 and 32 bit id generation
> [PLAT-10693] Create simple generator for span and trace IDs

- jest.config.js
- packages/platforms/react-native/lib/config.ts
- packages/platforms/react-native/lib/index.ts
- packages/platforms/react-native/lib/resource-attributes-source.ts
- packages/platforms/react-native/lib/span-attributes-source.ts
- packages/platforms/react-native/package.json
- packages/platforms/react-native/rollup.config.mjs
- packages/platforms/react-native/tests/config.test.ts
- packages/platforms/react-native/tests/resource-attributes-source.test.ts
- packages/platforms/react-native/tsconfig.json
Create a publishable package for the react native performance client
Populated a react native client using the react native specific methods and the core `createClient` method.
Published to verdaccio and installed to a React Native 0.72 application running on a simulator.
**Span from Android:**
```
{
"resourceSpans": [
{
"resource": {
"attributes": [
{
"key": "deployment.environment",
"value": {
"stringValue": "production"
}
},
{
"key": "telemetry.sdk.name",
"value": {
"stringValue": "bugsnag.performance.reactnative"
}
},
{
"key": "telemetry.sdk.version",
"value": {
"stringValue": "1.0.0"
}
},
{
"key": "service.version",
"value": {
"stringValue": "0.0.1"
}
},
{
"key": "os.type",
"value": {
"stringValue": "linux"
}
},
{
"key": "os.name",
"value": {
"stringValue": "android"
}
},
{
"key": …
```
> [PLAT-10650] Create react native package

- test/react-native/features/fixtures/scenario-launcher/scenarios/NestedSpansScenario.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/index.js
- test/react-native/features/nested-spans.feature
Add end to end tests to ensure spans assume the current parent
> [PLAT-10800] Test nested spans

- packages/platforms/react-native/lib/id-generator.ts
> Generate ids by only iterating over a single array

- package-lock.json
Update package-lock file to latest dependencies.
Relied on CI.
> build: update package-lock

- packages/platforms/react-native/lib/client.ts
- packages/platforms/react-native/lib/resource-attributes-source.ts
- packages/platforms/react-native/tests/resource-attributes-source.test.ts
Pass persistence to the resource attribute source so it's a) customisable and b) can be shared with the client
> Pass persistence to the resource attribute source

- .buildkite/browser-pipeline.yml
- .buildkite/react-native-pipeline.yml
Align the Buildkite concurrency group for BitBar to match all other repos.
Covered by CI.
> Update Buildkite concurrency group

- packages/platforms/react-native/lib/persistence/file-based.ts
- packages/platforms/react-native/lib/persistence/file.ts
- packages/platforms/react-native/lib/persistence/index.ts
- packages/platforms/react-native/tests/persistence/file-based.test.ts
- packages/platforms/react-native/tests/persistence/file.test.ts
Read the device ID from the native SDKs if they are present so that they line up across spans from both JS and native
> Read device ID from native SDK if present

- CHANGELOG.md
Fix CHANGELOG for react native release
> [DOCS] Update CHANGELOG

- test/browser/features/fixtures/packages/react-router/src/index.jsx
Reduce number of flakes in end to end tests
> Increase maximum spans in react-router test

- .buildkite/browser-pipeline.full.yml
- .buildkite/browser-pipeline.yml
- .buildkite/react-native-pipeline.yml
Add an automatic retry to build steps within CI to improve stability
Covered by CI
> [PLAT-10810] Automatic retry on build steps

- test/react-native/features/persistent-state.feature
Reduce flakes in scenario by awaiting sampling request before creating new span
> [PLAT-11178] Update sampling probability test fixture

- package-lock.json
Update `@babel/traverse` dependency to resolve CVE-2023-45133
> [PLAT-11115] Update @babel/traverse

- packages/core/lib/config.ts
- packages/core/lib/core.ts
- packages/core/lib/validation.ts
- packages/core/tests/core.test.ts
- packages/core/tests/validation.test.ts
To add `getPlugin` functionality to the core client
Added unit test that a provided plugin is able to be retrieved and used
> [PLAT-11283] Add getPlugin method to core

- .buildkite/react-native-pipeline.yml
- Gemfile
Add Gemfile with `cocoapods` and `bundle install` to CI to ensure that builds work as expected
Covered by CI
> [PLAT-11248] Add Gemfile and `bundle install` to ensure CI runs work

- CHANGELOG.md
- package-lock.json
- packages/platforms/react-native/package.json
Reduce strictness of peer dependency requirements in the react-native-performance package
> [PLAT-11637] Reduce peer dependency strictness

- cuid.d.ts
- package-lock.json
- packages/core/lib/persistence.ts
- packages/core/lib/validation.ts
- packages/core/package.json
- packages/platforms/browser/package.json
- packages/platforms/browser/tsconfig.json
- packages/platforms/react-native/lib/persistence/file-based.ts
- packages/platforms/react-native/package.json
- packages/platforms/react-native/tsconfig.json
Use validation and type definitions from `@bugsnag/cuid` v3.1.0
> [PLAT-12014] Update @bugsnag/cuid

- packages/core/rollup.config.mjs
Found an issue with rollup configuration while building for release - release made from this branch
> Hotfix rollup config

- test/browser/features/fixtures/packages/oldest-batch-removed/src/index.js
- test/browser/features/retries.feature
Prevent flakes due to incorrect number of traces received
> Simplify retry queue test

- package-lock.json
Update package lock dependencies and run npm audit fix to resolve:
CVE-2023-45133
CVE-2023-49293, CVE-2024-23331, CVE-2024-31207
CVE-2024-29180
> May 2024 CVEs

- package-lock.json
- packages/platforms/react-native/package.json
Resolve CVE-2023-45133 by removing affected `babel-traverse` dependency
> [PLAT-11115] CVE-2023-45133 | babel-traverse 

- CHANGELOG.md
- dockerfiles/Dockerfile.license-finder
- package-lock.json
- package.json
- packages/core/lib/span-factory.ts
- packages/core/lib/span.ts
- packages/core/lib/validation.ts
- packages/core/tests/validation.test.ts
- packages/platforms/browser/lib/auto-instrumentation/full-page-load-plugin.ts
- packages/platforms/browser/tests/auto-instrumentation/full-page-load-plugin.test.ts
- packages/platforms/react-native/package.json
- packages/plugin-react-navigation/lib/navigation-context.tsx
- packages/plugin-react-navigation/test/create-navigation-container.test.tsx
- packages/plugin-react-navigation/test/navigation-context.test.tsx
- test/browser/Gemfile.lock
- test/browser/features/fixtures/packages/traceparent-meta/index.html
- test/browser/features/fixtures/packages/traceparent-meta/package.json
- test/browser/features/fixtures/packages/traceparent-meta/src/index.js
- test/browser/features/page-load-spans.feature
- (browser) Set parent span context for full page load spans based on traceparent meta tag, if present [#446](https://github.com/bugsnag/bugsnag-js-performance/pull/446)
- (plugin-react-navigation) Fix an issue where a navigation span could inherit the end time of the last span [#457](https://github.com/bugsnag/bugsnag-js-performance/pull/457)
> Release v2.6.0

- dockerfiles/Dockerfile.release
Fix release script
Released v2.6.0
> Add python setup tools separated in version 3.12

- test/browser/features/steps/browser-steps.rb
Remove custom step added to maze-runner in https://github.com/bugsnag/maze-runner/pull/661
> Remove duplicate double attribute step

- packages/core/lib/batch-processor.ts
- packages/core/lib/core.ts
- packages/core/lib/probability-manager.ts
- packages/core/tests/batch-processor.test.ts
- packages/core/tests/core.test.ts
- packages/core/tests/probability-manager.test.ts
- packages/platforms/browser/tests/browser.test.ts
> Sync integration branch with next

- .buildkite/react-native-navigation-pipeline.full.yml
- .buildkite/react-native-navigation-pipeline.yml
- .buildkite/react-native-pipeline.full.yml
- .buildkite/react-native-pipeline.yml
- package-lock.json
- packages/platforms/browser/package.json
- test/browser/features/fixtures/packages/error-correlation/package.json
Update Bugsnag notifier dependency to v8.0.0
> Bugsnag v8.0.0

- lerna.json
- package-lock.json
- package.json
Update Lerna to latest major version
> Upgrade lerna to v8

- CHANGELOG.md
- packages/platforms/browser/lib/id-generator.ts
Update Span and Trace ID generator code to allow for modified Array.from API
Chain id generator operations
Covered by CI run
> Refactor ID generator

- bin/generate-react-native-fixture
Repair React Native fixture generation script using deprecated flag
> Update deprecated --npm flag

- .buildkite/browser-pipeline.yml
- test/react-native/features/fixtures/scenario-launcher/android/build.gradle
- test/react-native/features/fixtures/scenario-launcher/lib/Persistence.js
Resolve issues in end to end tests
- Update Safari browser tests to 18
- Clear persisted device id on android
- Fix NoSuchMethodError in android tests
Full CI run
> Fix CI issues

- packages/delivery-fetch/tests/delivery.test.ts
The mock response of `{}` was causing the following error which was getting swallowed by a catch handler:
```
TypeError: Cannot read properties of undefined (reading 'get')
at samplingProbabilityFromHeaders (/Users/dan.skinner/bugsnag-js-performance/packages/delivery-fetch/lib/delivery.ts:7:25)
at Object.send (/Users/dan.skinner/bugsnag-js-performance/packages/delivery-fetch/lib/delivery.ts:68:34)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at Object.<anonymous> (/Users/dan.skinner/bugsnag-js-performance/packages/delivery-fetch/tests/delivery.test.ts:50:22)
```
```
try {
[...]
const response = await fetch(endpoint, {
method: 'POST',
keepalive,
body,
headers: payload.headers
})
return {
state: responseStateFromStatusCode(response.status),
samplingProbability: …
```
> fix delivery-fetch tests

- packages/platforms/react-native/android/src/main/java/com/bugsnag/android/performance/NativeBugsnagPerformanceImpl.java
- packages/platforms/react-native/android/src/newarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
- packages/platforms/react-native/android/src/oldarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
Replace react-native-file-access module with our own implementation for native file io.
Added implementation for the android native part.
Used existing mazerunner tests.
> Add android implementation for FileSystem operations

- packages/platforms/react-native/ios/BugsnagReactNativePerformance.mm
Replace `react-native-file-access` module with our implementation for file I/O.
Added implementation for filesystem methods for IOS.
Used existing maze-runner tests.
> Add ios implementation for FileSystem operations

- test/browser/features/fixtures/packages/react-router/package.json
- test/browser/features/fixtures/packages/route-change-spans/package.json
- test/browser/features/fixtures/packages/route-change-spans/src/app.jsx
Fix failing CI build by updating `react-router-dom` and `react-dom` dependencies.
> Update test fixture dependencies

- .github/workflows/scorecard.yml
Configure Open SSF scorecard github action
> Add Open SSF scorecard workflow

- .github/workflows/compare-pr-stats.yml
- .github/workflows/record-pr-stats.yml
Allow pull request write permissions to Compare PR stats action
> Allow pull request write permissions to Compare PR stats action

- .github/workflows/compare-pr-stats.yml
- README.md
- dockerfiles/Dockerfile.license-finder
- dockerfiles/Dockerfile.release
- examples/react-navigation/android-fragments/osv-scanner.toml
- examples/rn072/osv-scanner.toml
- package-lock.json
Implement changes recommended by OpenSSF Scorecard scan
> OpenSSF improvements

- .github/workflows/scorecard.yml
Update scorecard action to `2.4.1` to inherit latest osv-scanner changes
> Update scorecard action

- bin/generate-react-native-fixture
Resolve issues building React Native test fixtures
> Pin @react-native-community/cli to v16

- test/browser/features/component-lifecycle-spans.feature
- test/browser/features/fixtures/packages/react-router/rollup.config.mjs
- test/browser/features/fixtures/packages/react-router/src/index.jsx
Test component lifecycle spans with react-router
> Add react-router tests

- package-lock.json
Revert changes to the package-lock file caused by the release process (aside from the appropriate package version updates)
> [Hotfix] Revert package-lock.json changes

- test/browser/features/angular.feature
- test/browser/features/fixtures/packages/angular/src/index.html
Reinstate skipped angular end to end tests
Covered by existing ci
> Reinstate angular end to end tests

- package-lock.json
A bug in the release script caused a lot of undesired changes to the lockfile when publishing.
This PR reverts these changes and restores the lockfile to the expected state on `main`.
Reverted the lockfile changes from the release and ran `npm install` to re-apply the correct changes.
Once this is all merged back into `next` I'll raise a separate PR to fix the release script.
> Fix package-lock.json after release

- packages/svelte-kit/package.json
Add missing fields to the `package.json` for `@bugsnag/svelte-kit-performance`
> Hotfix: svelte-kit package.json update

- .buildkite/browser-pipeline.yml
- .buildkite/react-native-pipeline.full.yml
- .buildkite/react-native-pipeline.yml
Move remaining macos-14 steps to macos-15
Covered by CI
> Move remaining macos-14 steps to macos-15

- .buildkite/react-native-pipeline.full.yml
- .buildkite/react-native-pipeline.yml
- bin/generate-react-native-fixture
Add React Native 0.80 tests to CI test matrix
Covered by CI
> Add React Native 0.80 tests

- lerna.json
- package-lock.json
- packages/angular/package.json
- packages/core/package.json
- packages/delivery-fetch/package.json
- packages/platforms/browser/package.json
- packages/platforms/react-native/package.json
- packages/plugin-named-spans/package.json
- packages/plugin-react-native-navigation/package.json
- packages/plugin-react-native-span-access/package.json
- packages/plugin-react-navigation/package.json
- packages/plugin-react-performance/package.json
- packages/request-tracker/package.json
- packages/svelte-kit/package.json
Sync next with main following v2.15.0 release
> v2.15.0 post-release merge
