- packages/platforms/js/package.json
Required to publish js meta package
> Add public access to publish config

- packages/core/lib/core.ts
- packages/core/lib/span.ts
- packages/core/tests/span.test.ts
- packages/platforms/browser/lib/auto-instrumentation/route-change-plugin.ts
- packages/platforms/browser/lib/browser.ts
- packages/platforms/browser/tests/route-change-plugin.test.ts
- packages/platforms/browser/tests/routing-provider.test.ts
- packages/test-utilities/lib/mock-span-factory.ts
Introduces a `SpanContext` interface that exposes a span's `id` and `traceId` as readonly properties, as well as an `isValid()` method which returns a boolean indicating whether the span is still valid (open)
Both `Span` and `SpanInternal` now implement the `SpanContext` interface.
A convenience function `spanContextEquals` has also been added to compare two `SpanContext` instances - this isn't used yet but will be used in future to ensure the correct context is popped from the context stack
The creation of the public `Span` instances (as well as the start/end time sanitization) has been moved into the span factory, since we already do this in a couple of places
> [PLAT-10224] Add `SpanContext` interface

- CHANGELOG.md
- packages/core/lib/core.ts
- packages/core/lib/span.ts
- packages/core/tests/span.test.ts
- packages/test-utilities/lib/mock-span-factory.ts
To notify users why a no-op has occurred when ending an already ended span
Construct a span factory with the platform schema default logger, swapping it out with a provided logger when a user calls `.start`
Add unit test that checks a logger is called when a cancelled (backgrounded) span is ended
Add unit test that checks a logger is called when a span is ended multiple times
> [PLAT-10258] Add warning when calling Span.end multiple times

- packages/core/lib/core.ts
- packages/platforms/browser/lib/browser.ts
- packages/test-utilities/lib/create-test-client.ts
First in a stack of PRs to start persisting sampling probabilities
This PR adds `persistence` to `ClientOptions`
> Add 'persistence' as a client option

- packages/core/lib/probability-fetcher.ts
- packages/core/tests/probability-fetcher.test.ts
Usage:
```ts
const probabilityFetcher = new ProbabilityFetcher(delivery)
const probability: number = await probabilityFetcher.getNewProbability()
// do stuff with 'probability'
```
This will normally make 1 request but if the request fails or the server doesn't return a sampling probability it will retry until a probability is available
This abstraction will help to remove some of the complexity from the `Sampler` class as it got very tricky to deal with when adding persistence on top of the period requests
> Add ProbabilityFetcher abstraction for getting probabilities from the pipeline

- packages/core/lib/probability-manager.ts
- packages/core/tests/probability-manager.test.ts
Add a new `ProbabilityManager` that handles persistence and period requests for sampling. Anyone needing to update the sampling probability will use this instead of updating the `Sampler` directly
On `start` it handles the interplay between persistence and the initial request (see comments):
```ts
const probabilityManager = await ProbabilityManager.create(
options.persistence,
sampler,
configuration.samplingProbability,
probabilityFetcher
)
```
Then when the probability is updated:
```ts
probabilityManager.setProbability(newProbability)
```
> Add abstraction for managing probabilities

- packages/core/lib/batch-processor.ts
- packages/core/lib/core.ts
- packages/core/lib/probability-manager.ts
- packages/core/lib/sampler.ts
- packages/core/lib/span.ts
- packages/core/tests/batch-processor.test.ts
- packages/core/tests/core.test.ts
- packages/core/tests/sampler.test.ts
- packages/core/tests/span.test.ts
- packages/platforms/browser/tests/page-load-span-plugin.test.ts
- packages/platforms/browser/tests/route-change-plugin.test.ts
- packages/platforms/browser/tests/routing-provider.test.ts
- test/browser/features/support/isolate-scenarios.rb
This PR integrates the `ProbabilityManager` (#205) with `BugsnagPerformance#start` and the `BatchProcessor`
Most of the changes here are swapping `jest.runOnlyPendingTimers()` to `await jest.runOnlyPendingTimersAsync()` as there's now a promise in `start` — `PerformanceManager.create` is async as it needs to read from persisted storage
I've also added two new interfaces for `Sampler` — `ReadonlySampler` and `ReadWriteSampler`. Using `ReadonlySampler` means you can't update the probability value, since that should always go through the `ProbabilityManager`. This obviously isn't foolproof but hopefully should help prevent bugs due to not persisting probabilities in future
The e2e tests also clear local storage after running so that tests can't interfere with each other if they set different …
> Persist sampling changes

- packages/core/lib/core.ts
- packages/core/tests/core.test.ts
Adds a new `spanContextStorage` client option for platforms to provide their own implementation. There are currently no platforms-specific implementations, so this is optional - if no implementation is provided then `DefaultSpanContextStorage` is used.
Also adds `currentSpanContext` as a new readonly property to the client to allow users to retrieve the current context and use it manually if they need to (for example starting multiple spans under the same parent context)
> Make `SpanContextStorage` a client option and add `currentSpanContext` to client

- packages/core/lib/core.ts
- packages/core/lib/span.ts
- packages/core/tests/span.test.ts
- packages/test-utilities/lib/mock-span-factory.ts
This PR adds a new optional `makeCurrentContext` option to `SpanOptions`
```diff
- startSpan(name: string, options?: { startTime?: Time })
+ startSpan(name: string, options?: { startTime?: Time, makeCurrentContext?: boolean })
```
Unless this is explicitly set to `false`,  starting a span will push it onto the context stack making it the 'current' `SpanContext`
When a span is ended, it will be popped off the context stack (if it is the current `SpanContext`)
> Add `makeCurrentContext` to `SpanOptions`

- packages/platforms/browser/lib/auto-instrumentation/network-request-plugin.ts
- packages/platforms/browser/tests/network-request-plugin.test.ts
This PR prevents auto-instrumented network spans from becoming the current span context, since network spans should not have any children
> Prevent network spans from becoming the current span context

- .github/create-browser-bundle-from-npm
- package-lock.json
- packages/core/lib/attributes.ts
- packages/core/lib/batch-processor.ts
- packages/core/lib/persistence.ts
- packages/core/tests/batch-processor.test.ts
- packages/core/tests/core.test.ts
- packages/core/tests/persistence.test.ts
- packages/platforms/browser/cuid.d.ts
- packages/platforms/browser/lib/browser.ts
- packages/platforms/browser/lib/config.ts
- packages/platforms/browser/lib/persistence.ts
- packages/platforms/browser/lib/resource-attributes-source.ts
- packages/platforms/browser/package.json
- packages/platforms/browser/rollup.config.mjs
- packages/platforms/browser/tests/persistence.test.ts
- packages/platforms/browser/tests/resource-attributes-source.test.ts
- packages/platforms/browser/tests/route-change-plugin.test.ts
- packages/platforms/browser/tsconfig.json
- packages/test-utilities/lib/create-configuration.ts
- packages/test-utilities/lib/resource-attributes-source.ts
- test/browser/features/device-id.feature
- test/browser/features/fixtures/package.json
- test/browser/features/fixtures/packages/rollup.config.mjs
- test/browser/features/manual-spans.feature
- test/browser/features/steps/browser-steps.rb
Add `device.id` as a resource attribute using `@bugsnag/cuid` and the `bugsnag-anonymous-id` key so the IDs are shared with the notifier: https://github.com/bugsnag/bugsnag-js/blob/next/packages/plugin-browser-device/device.js
This required changing `ResourceAttributeSource` to be asynchronous as we need to fetch the device ID from persistence at least once but can't until we've read the `generateAnonymousId` config option
> Add `device.id` as a resource attribute

- packages/core/lib/span.ts
- packages/core/tests/span.test.ts
- packages/platforms/browser/lib/auto-instrumentation/route-change-plugin.ts
- packages/platforms/browser/lib/routing-provider.ts
- packages/platforms/browser/lib/span-attributes-source.ts
- packages/platforms/browser/tests/span-attributes-source.test.ts
- test/browser/features/fixtures/packages/manual-span/src/index.js
- test/browser/features/manual-spans.feature
- test/browser/features/route-change-spans.feature
Add `isFirstClass` span option controlling the `bugsnag.span.first_class` attribute
This defaults to `true` for all spans (custom, network, page load & route changes) and can be set to `false` for custom spans only
This necessitated changing the `StartRouteChangeCallback` options parameter to omit `isFirstClass` as route change spans are always first class (this is the same for network and page load spans but users can't supply options for those span types)
> Add `isFirstClass` span option controlling the `bugsnag.span.first_class` attribute

- packages/core/lib/core.ts
- packages/core/lib/probability-manager.ts
- packages/core/tests/batch-processor.test.ts
- packages/core/tests/config.test.ts
- packages/core/tests/probability-manager.test.ts
- packages/core/tests/span.test.ts
- packages/test-utilities/lib/create-configuration.ts
Remove 'samplingProbability' configuration option. Instead we use a default probability of 1.0 until we receive a value from the server
> Remove 'samplingProbability' configuration option

- packages/core/lib/delivery.ts
- packages/core/lib/span.ts
- packages/core/lib/validation.ts
- packages/core/tests/span.test.ts
- packages/test-utilities/lib/incrementing-id-generator.ts
- packages/test-utilities/lib/index.ts
- test/browser/features/fixtures/packages/nested-spans/index.html
- test/browser/features/fixtures/packages/nested-spans/package.json
- test/browser/features/fixtures/packages/nested-spans/src/index.js
- test/browser/features/nested-spans.feature
This PR adds a new optional `parentContext` option to `SpanOptions`
```ts
interface SpanOptions {
parentContext?: SpanContext | null
}
```
A new optional `parentSpanId` field has also been added to internal and delivery spans - this is only set if the span has a parent
When a `parentContext` is specified in `SpanOptions`, the created span will become a child of that context. This means that the span's `parentSpanId` will be set to the parent's `id`, and the span's `traceId` will be set to the parent's `traceId`.
If no `parentContext` is specified, by default new spans will become children of `currentSpanContext`. 
if there is no `currentSpanContext`, or `parentContext` is set explicitly to `null`, the created span is a new root span - this means `parentSpanId` is not set and a new …
> Add `parentContext` to `SpanOptions` and set parentage for new spans

- test/browser/features/lib/browser.rb
- test/browser/features/lib/url-generator.rb
- test/browser/features/steps/browser-steps.rb
- test/browser/features/support/isolate-scenarios.rb
- test/browser/features/support/maze-config.rb
We need $browser to be available at all times so that we can use it for things like the 'skip' annotations. This was problematic as it was created in a 'before' hook, which run just before a scenario starts, so if a skip annotation required checking the $browser object then we'd crash
The $browser global needed to be in a before hook because it used the Maze Runner URLs for generating URLs to fixtures and those were only available after configuration is setup. This is now handled by a separate $url_generator object, which means the $browser object can be made available at all times
> Make sure the $browser global is always available in e2e tests

- packages/core/tests/batch-processor.test.ts
- packages/core/tests/probability-fetcher.test.ts
- packages/core/tests/span.test.ts
- packages/test-utilities/lib/in-memory-delivery.ts
Fix infinite timeouts in unit tests caused by `InMemoryDelivery` not returning a `samplingProbability` unless explicitly configured to do so
Now it will always return `samplingProbability: 1.0` if there is no override on its stack of probabilities
This ensures [`ProbabilityFetcher#getNewProbability`](https://github.com/bugsnag/bugsnag-js-performance/blob/ba836677042a81fcfa3bba0de44c7589d8e598a8/packages/core/lib/probability-fetcher.ts#L17-L30) will always resolve with a value
As part of this `InMemoryDelivery` must now also allow `undefined` to be set as a `samplingProbability` so that it can be told to not return one at all
> Fix unit test timeouts

- packages/core/lib/span.ts
- packages/core/tests/span.test.ts
It will be fairly common for a span to be discarded before being ended as we do this automatically when the page is backgrounded
Now we will only warn if a span is explicitly ended multiple times
> Don't warn when a span was discarded before ending

- packages/core/lib/span.ts
- packages/platforms/browser/lib/auto-instrumentation/full-page-load-plugin.ts
- packages/platforms/browser/tests/auto-instrumentation/page-load-span-plugin.test.ts
- packages/platforms/browser/tests/page-load-span-plugin.test.ts
Currently we start and end full page load spans after the page has settled so that we can resolve the route - however we now need to start (and end) child spans  such as resource load spans before the page has settled, so the full page load span needs to be started earlier.
This PR updates the full page load plugin to start the span as soon as the plugin is configured, and then update the name with the route once the page has settled.
The full page load span now also passes `parentContext: null` when starting the span to ensure that it is always a root span (with no parent)
> Start FullPageLoad spans earlier

- packages/platforms/browser/lib/delivery.ts
- packages/platforms/browser/tests/delivery.test.ts
This reverts commit 15928b2c75d08dfdcdcf6505267d73274f3cd304.
This causes a CORS error because "Bugsnag-Sent-At" is not in "Access-Control-Allow-Headers":
> Access to fetch at 'https://otlp.bugsnag.com/v1/traces' from origin '$origin' has been blocked by CORS policy: Request header field bugsnag-sent-at is not allowed by Access-Control-Allow-Headers in preflight response.
This wasn't caught by e2e tests because it's in Maze Runner's list of allowed headers
> Remove 'Bugsnag-Sent-At' header

- packages/platforms/browser/lib/auto-instrumentation/page-load-phase-spans.ts
- packages/platforms/browser/tests/auto-instrumentation/page-load-phase-spans.test.ts
- test/browser/features/page-load-spans.feature
Sets the following required attributes for page load phase spans:
`bugsnag.span.category: page_load_phase`
`bugsnag.phase: Phase`
> Set category and phase attributes on page load phase spans

- packages/core/lib/core.ts
- packages/core/lib/span-context.ts
- packages/core/lib/span-factory.ts
- packages/platforms/browser/lib/auto-instrumentation/index.ts
- packages/platforms/browser/lib/auto-instrumentation/resource-load-plugin.ts
- packages/platforms/browser/lib/browser.ts
- packages/platforms/browser/tests/auto-instrumentation/resource-load-plugin.test.ts
- packages/platforms/browser/tests/utilities/performance-entry.ts
- test/browser/features/fixtures/packages/page-load-spans/src/index.js
- test/browser/features/fixtures/packages/resource-load-spans/index.html
- test/browser/features/fixtures/packages/resource-load-spans/package.json
- test/browser/features/fixtures/packages/resource-load-spans/src/index.js
- test/browser/features/lib/browser.rb
- test/browser/features/resource-load-spans.feature
- test/browser/features/support/requires-performance-body-size.rb
- test/browser/features/support/requires-performance-response-status.rb
- test/browser/features/support/requires-resource-load-spans.rb
Implement a new ResourceLoadPlugin in the browser client, to enable automatic instrumentation of resource load spans when there is an open span in the context stack
Unit tests for automatic span creation with correct parentage
Unit test fetch/xhr requests do not create resource load spans
Unit test resource load spans are not created when there is no parent context
End to end tests for automated resource load spans with correct parentage
> [PLAT-10231] ResourceLoad spans

- bin/cdn-upload
- package-lock.json
- package.json
This is "inspired" by [the one in @bugsnag/js](https://github.com/bugsnag/bugsnag-js/blob/21836527fd91b01020135bbb94ccf93ecdaa1c59/bin/cdn-upload) but updated to use AWS' v3 packages
Run it in much the same way:
```sh
$ npm run cdn-upload
```
Tested against the sandbox AWS bucket/cloudfront distribution
> Add CDN upload script

- bin/release.sh
- docker-compose.yml
- dockerfiles/Dockerfile.release
Adapted the release script and process from the `@bugsnag/js` repo with a few tweaks for the performance library. 
Run in much the same way:
- `docker compose build release`
- (with relevant environment variables set) `docker compose run release`
> Add release script

- test/browser/features/fixtures/packages/page-load-spans/src/index.js
- test/browser/features/page-load-spans.feature
- test/browser/features/steps/browser-steps.rb
Test the `bugsnag.browser.page.referrer` attribute is validated in end to end tests
> [PLAT-10176] Referrer attribute testing

- jest.config.js
- package-lock.json
- package.json
Adds an npm script and jest configuration for generating code coverage reports, as well as a dev dependency on `coverage-diff` for generating the comparison table for the PR comment
PR'd separately because the coverage script and configuration are needed in both of the branches being compared
> Add code coverage script and config

- packages/core/lib/core.ts
- packages/core/lib/span-factory.ts
- packages/core/lib/span.ts
- packages/core/lib/validation.ts
- packages/core/tests/span-context.test.ts
- packages/core/tests/span-factory.test.ts
- packages/core/tests/span.test.ts
- packages/core/tests/validation.test.ts
- packages/platforms/browser/lib/auto-instrumentation/route-change-plugin.ts
- packages/platforms/browser/tests/auto-instrumentation/route-change-plugin.test.ts
- packages/test-utilities/lib/mock-span-factory.ts
This PR adds validation to inputs when starting spans, both via `BugsnagPerformance.startSpan` and the `startRouteChangeSpan` callback in routing providers.
Takes a similar approach to config validation, adding a generic validation function and a core span options schema that can be extended by different platforms/plugins (see `route-change-plugin.ts`)
If an input is invalid, a warning is logged and the default value is used instead. For all SpanOptions this is `undefined` and for span names the invalid input is converted to a string. 
Updated and added unit tests for input validation and reorganised the span and span factory unit tests to split out tests for invalid options from the actual implementation of each option
> Handle invalid inputs to startSpan

- packages/core/lib/batch-processor.ts
- packages/core/lib/sampler.ts
- packages/core/lib/span.ts
- packages/test-utilities/lib/create-span.ts
Currently we only store the scaled probability value on a `SpanEnded` as its `samplingProbability`. However, we need the raw value (between 0-1) in order to calculate the `Bugsnag-Span-Sampling` header and to store in the `bugsnag.sampling.p` attribute
This PR updates `samplingProbability` to be an object with both the raw and scaled probability values
> Store both the raw and scaled probability on spans

- packages/platforms/browser/lib/auto-instrumentation/route-change-plugin.ts
- packages/platforms/browser/lib/default-routing-provider.ts
- packages/platforms/browser/lib/routing-provider.ts
- packages/platforms/browser/tests/auto-instrumentation/route-change-plugin.test.ts
- packages/platforms/browser/tests/utilities/mock-routing-provider.ts
- test/browser/features/page-load-spans.feature
- test/browser/features/route-change-spans.feature
Ensure `bugsnag.browser.page.url` attribute accurately reflects the new url after a route change
Added a new url parameter to `startRouteChangeSpan` callback in `listenForRouteChanges`
Updated end to end tests
> Validate bugsnag.browser.page.url

- CHANGELOG.md
- packages/platforms/browser/lib/auto-instrumentation/resource-load-plugin.ts
- packages/platforms/browser/tests/auto-instrumentation/resource-load-plugin.test.ts
- packages/test-utilities/lib/span-attributes-source.ts
To only add an `http.flavor` span attribute if it is a usable value.
Updated unit tests
> [PLAT-10560] Remove empty http.flavor span attribute

- CHANGELOG.md
- packages/platforms/browser/lib/auto-instrumentation/network-request-plugin.ts
- packages/platforms/browser/lib/config.ts
- packages/platforms/browser/tests/auto-instrumentation/network-request-plugin.test.ts
- packages/test-utilities/lib/create-configuration.ts
To remove an option that will be covered by new functionality in the network span controls callback.
> [PLAT-10511] Remove networkInstrumentationIgnoreUrls option

- packages/core/lib/clock.ts
- packages/core/tests/time.test.ts
- packages/platforms/browser/lib/browser.ts
- packages/platforms/browser/lib/clock.ts
- packages/platforms/browser/lib/delivery.ts
- packages/platforms/browser/tests/clock.test.ts
- packages/platforms/browser/tests/delivery.test.ts
- packages/test-utilities/lib/incrementing-clock.ts
Use `Clock` to set the `Bugsnag-Sent-At` header. This requires a new `Clock#date` function that returns a `Date` object
> Use `Clock` to set the `Bugsnag-Sent-At` header

- .github/leave-pr-stats-comment.js
Reduces the 'fail' threshold for the code coverage reporting tool from 100% to 90%. 
The decrease threshold is still 0 so any percentage decrease in a file's coverage will be reported as a 'fail'
> Reduce code coverage failure threshold

- CHANGELOG.md
- packages/platforms/browser/lib/config.ts
- packages/platforms/browser/lib/network-request-callback.ts
- packages/platforms/browser/tests/network-request-callback.test.ts
Add a new configuration option to modify the url of network spans return null (can be used by the network span and resource load span plugins to prevent span creation)
Added unit tests for `defaultNetworkRequestCallback` and `isNetworkRequestCallback` validation function
> [PLAT-10601] Add networkRequestCallback config option

- CHANGELOG.md
- packages/platforms/browser/lib/auto-instrumentation/network-request-plugin.ts
- packages/platforms/browser/lib/network-request-callback.ts
- packages/platforms/browser/lib/request-tracker/request-tracker-fetch.ts
- packages/platforms/browser/lib/request-tracker/request-tracker-xhr.ts
- packages/platforms/browser/lib/request-tracker/request-tracker.ts
- packages/platforms/browser/tests/auto-instrumentation/network-request-plugin.test.ts
- packages/platforms/browser/tests/network-request-callback.test.ts
- packages/platforms/browser/tests/on-settle/index.test.ts
- packages/platforms/browser/tests/on-settle/request-settler.test.ts
- packages/platforms/browser/tests/request-tracker/request-tracker-fetch.test.ts
- packages/platforms/browser/tests/request-tracker/request-tracker-xhr.test.ts
- packages/platforms/browser/tests/request-tracker/request-tracker.test.ts
- packages/test-utilities/lib/create-configuration.ts
use the `networkRequestCallback` plugin in the `network-span-plugin` in order to use the modified url or prevent creation of spans.
Unit tests to ensure modified URLs are used by `network-span-plugin`
Unit tests to ensure spans are not created when `networkRequestCallback` returns `null`
> [PLAT-10604] Implement networkRequestCallback in Network Span Plugin

- CHANGELOG.md
- packages/core/lib/attributes.ts
- packages/core/lib/core.ts
- packages/core/lib/span-factory.ts
- packages/core/tests/span.test.ts
- packages/platforms/browser/lib/auto-instrumentation/full-page-load-plugin.ts
- packages/platforms/browser/lib/auto-instrumentation/network-request-plugin.ts
- packages/platforms/browser/lib/auto-instrumentation/page-load-phase-spans.ts
- packages/platforms/browser/lib/auto-instrumentation/resource-load-plugin.ts
- packages/platforms/browser/lib/auto-instrumentation/route-change-plugin.ts
- packages/platforms/browser/lib/browser.ts
- packages/platforms/browser/lib/config.ts
- packages/platforms/browser/lib/send-page-attributes.ts
- packages/platforms/browser/lib/span-attributes-source.ts
- packages/platforms/browser/tests/auto-instrumentation/network-request-plugin.test.ts
- packages/platforms/browser/tests/auto-instrumentation/page-load-span-plugin.test.ts
- packages/platforms/browser/tests/auto-instrumentation/resource-load-plugin.test.ts
- packages/platforms/browser/tests/auto-instrumentation/route-change-plugin.test.ts
- packages/platforms/browser/tests/on-settle/index.test.ts
- packages/platforms/browser/tests/routing-provider.test.ts
- packages/platforms/browser/tests/send-page-attributes.test.ts
- packages/platforms/browser/tests/span-attributes-source.test.ts
- packages/test-utilities/lib/mock-span-factory.ts
- packages/test-utilities/lib/span-attributes-source.ts
- test/browser/features/page-load-spans.feature
Add a new configuration option to manually exclude `url`, `title` and `referrer` attributes from automatically instrumented spans
Unit tests for validation functions
> [PLAT-10602] Add `sendPageAttributes` configuration option

- CHANGELOG.md
- packages/platforms/browser/lib/auto-instrumentation/full-page-load-plugin.ts
- packages/platforms/browser/tests/auto-instrumentation/page-load-span-plugin.test.ts
Thwart the adding of span attributes in full page loads based on values set in `sendPageAttributes` configuration
Added a new unit test to ensure span attributes are not added when matching properties are set to `false`
> [PLAT-10602] Implement configuration.sendPageAttributes in full page load plugin

- CHANGELOG.md
- packages/platforms/browser/lib/auto-instrumentation/full-page-load-plugin.ts
- packages/platforms/browser/lib/auto-instrumentation/route-change-plugin.ts
- packages/platforms/browser/tests/auto-instrumentation/page-load-span-plugin.test.ts
- packages/platforms/browser/tests/auto-instrumentation/route-change-plugin.test.ts
Prevent adding span attributes in full page loads based on values set in `sendPageAttributes` configuration
Added a new unit test to ensure span attributes are not added when matching properties are set to `false`
> [PLAT-10602] Implement configuration.sendPageAttributes in route-change-plugin

- CHANGELOG.md
- packages/platforms/browser/lib/auto-instrumentation/network-request-plugin.ts
- packages/platforms/browser/tests/auto-instrumentation/network-request-plugin.test.ts
Prevent errors in the pipeline from sending spans caused by network requests over additional protocols to http and https.
Prevent spans being created with urls starting with anything other than http and https, or using a relative path.
Added unit tests for positive and negative scenarios
> [PLAT-10617] Only track network requests over http(s)

- CHANGELOG.md
- packages/platforms/browser/lib/auto-instrumentation/route-change-plugin.ts
- packages/platforms/browser/lib/default-routing-provider.ts
- packages/platforms/browser/tests/default-routing-provider.test.ts
To prevent empty attributes in route change spans
> [PLAT-10639] Use pathname when resolved route is empty

- test/browser/features/fixtures/packages/network-span-control/index.html
- test/browser/features/fixtures/packages/network-span-control/package.json
- test/browser/features/fixtures/packages/network-span-control/src/index.js
- test/browser/features/network-spans.feature
- test/browser/features/page-load-spans.feature
- test/browser/features/steps/browser-steps.rb
Test network span control changes across supported browsers
Add end to end tests for modifying urls and preventing delivery of spans using networkRequestCallback config option
Add end to end tests for removing span attributes using sendPageAttribute config option
> [PLAT-10605] Add end to end tests

- packages/core/lib/config.ts
Updates the endpoint config validation to reject empty strings - discovered when creating the RN test fixture
> An empty string should not be considered a valid endpoint

- cuid.d.ts
- package-lock.json
- packages/core/lib/persistence.ts
- packages/core/lib/validation.ts
- packages/platforms/browser/lib/persistence.ts
- packages/platforms/browser/tsconfig.json
- packages/platforms/react-native/__mocks__/@react-native-async-storage/async-storage.ts
- packages/platforms/react-native/lib/config.ts
- packages/platforms/react-native/lib/persistence.ts
- packages/platforms/react-native/lib/resource-attributes-source.ts
- packages/platforms/react-native/package.json
- packages/platforms/react-native/rollup.config.mjs
- packages/platforms/react-native/tests/resource-attributes-source.test.ts
- packages/platforms/react-native/tsconfig.json
- test/react-native/features/fixtures/performance-scenarios/scenarios/ManualSpanScenario.js
- test/react-native/features/manual-spans.feature
Generate and persist device IDs using `@bugsnag/cuid` and `async-storage`
- Move `cuid` ts declaration to root and share between required ts configs
- Move persisted payload validation to core package to share between browser and react native
- Add config option to react-native
- Add persistence to react-native using `async-storage` falling back to in-memory persistence when not available
Test `device.id` attribute matches the expected regex in resource attribute source unit tests
> [PLAT-10654] Generate and persist device ID

- CHANGELOG.md
- packages/platforms/browser/lib/auto-instrumentation/full-page-load-plugin.ts
- packages/platforms/browser/tests/auto-instrumentation/page-load-span-plugin.test.ts
For route change spans we fallback to the default route resolver when a configured `routingProvider` does not return a route. However we don't do the same thing for full page load spans
This PR unifies this logic so that full page load spans will also always have a route
> Ensure full page load spans always have a route

- packages/platforms/react-native/lib/auto-instrumentation/app-start-plugin.tsx
- packages/platforms/react-native/lib/config.ts
- packages/platforms/react-native/tests/config.test.ts
- test/react-native/features/app-start-spans.feature
- test/react-native/features/fixtures/scenario-launcher/scenarios/WrapperComponentProviderScenario.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/index.js
React native's `AppRegistry` only permits one `WrapperComponentProvider` per app and there isn't a way to retrieve an existing one.
This PR adds a new configuration option named `wrapperComponentProvider` which allows users to provide their own `WrapperComponentProvider` if they are already using one. 
If provided, the app start wrapper component will be used to wrap the user-provided wrapper component, so that the app start instrumentation wrapper is still at the root.
This is difficult to unit test effectively - relies instead on a new e2e test scenario that asserts both that the the app start is instrumented and the supplied wrapper component is rendered as expected
> Add wrapperComponentProvider config option (React Native)

- packages/platforms/react-native/lib/clock.ts
Remove the logic that prevents the clock from moving backwards in react native, if the clock were to drift back by a significant amount (say, from changing timezone) - every span in the future would keep using exactly the same timestamp.
> Prevent React Native clock from sticking

- packages/platforms/react-native/lib/client.ts
- packages/platforms/react-native/lib/span-attributes-source.ts
- packages/platforms/react-native/tests/span-attributes-source.test.ts
- test/react-native/features/app-start-spans.feature
- test/react-native/features/fixtures/scenario-launcher/scenarios/BackgroundSpanScenario.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/index.js
- test/react-native/features/manual-spans.feature
- test/react-native/features/navigation-spans.feature
Add a new `bugsnag.app.in_foreground` span attribute
Use `ReactNative.AppState.currentState` to get the status of a span when it is created. 
- Refactor `spanAttributeSource` to enable providing `appState` as a parameter to simplify testing
- Add new attribute to `requestAttributes` method
- Add unit test for `true|false` attribute values
- Update all end-to-end tests to expect the new attribute
> [PLAT-10809] Add bugsnag.app.in_foreground span attribute

- docker-compose.yml
The "[Build Legacy Maze Runner image (CDN)](https://buildkite.com/bugsnag/bugsnag-js-performance/builds/2179#018a7438-41ee-497a-89f0-592a2e795166)" step doesn't actually run against the CDN build because the `USE_CDN_BUILD` arg isn't listed in `docker-compose.yaml`
This PR fixes that: https://buildkite.com/bugsnag/bugsnag-js-performance/builds/2179#018a7438-41ee-497a-89f0-592a2e795166/213-461
> Add `USE_CDN_BUILD` to args

- test/react-native/features/fixtures/scenario-launcher/scenarios/BackgroundSpanScenario.js
The AppState listener was added when the file was imported, which happens in every scenario
This now uses a useEffect hook so the subscription only happens when the component is mounted and unsubscribes when unmounted
This ensures it only runs when the BackgroundStateScenario is run
> Fix backgrounding scenario listening on load

- packages/core/lib/core.ts
- packages/core/lib/retry-queue.ts
- packages/platforms/browser/lib/browser.ts
- packages/platforms/react-native/lib/client.ts
- packages/test-utilities/lib/create-test-client.ts
This will allow the React Native SDK to implement its own RetryQueue
> Add a client option for customising the RetryQueue

- packages/core/lib/persistence.ts
- packages/core/lib/validation.ts
- packages/core/tests/validation.test.ts
`isPersistedProbabilty` &rarr; `isPersistedProbability`
> Fix typo in 'isPersistedProbability' function name

- packages/core/lib/batch-processor.ts
- packages/core/lib/retry-queue.ts
- packages/platforms/browser/lib/persistence.ts
Prefer 'satisfies never' to the '_exhaustiveCheck' we've been using in most places. This leads to less code in the compiled JavaScript
> Prefer 'satisfies never' to '_exhaustiveCheck'

- package-lock.json
- packages/platforms/react-native/__mocks__/react-native-file-access.ts
- packages/platforms/react-native/lib/persistence/file.ts
- packages/platforms/react-native/package.json
- packages/platforms/react-native/tests/persistence/file.test.ts
Adds an abstraction for reading & writing files using [the `react-native-file-access` library](https://github.com/alpha0010/react-native-file-access)
This is step 1 to supporting the `Persistence` interface in the React Native SDK backed by a JSON file
> Add file abstraction

- packages/platforms/react-native/__mocks__/react-native.ts
- packages/platforms/react-native/lib/native.ts
- packages/platforms/react-native/tests/resource-attributes-source.test.ts
When adding more native code, I found the existing React Native mock didn't quite work as expected. Notably it requires tests to add additional mocking in the test file itself, which causes some redundancy and makes it easy to do the wrong thing
This PR improves the RN mock so that no additional mocking is required in the tests themselves. I've also added support for multiple platforms (iOS is still the default) so that any different behaviour on Android can be tested as well. While we still need e2e tests to prove it works on devices, it's a lot easier & quicker to run the unit tests while developing
> Improve react-native mock

- .buildkite/browser-pipeline.yml
NOTE: Please let me merge this PR myself, it needs to be merged as the same time as several others to avoid unnecessary failures on CI.
Rationalise the Buildkite concurrency group used to control access to BitBar across all of our repos.
We were using separate groups fro web and device usage, when in fact they are counted towards the same usage limit.  All groups are now being renamed to simply 'bitbar' with a limit of 25.
The main mistake that I could make here is missing an instance of the old groups (`bitbar-app` and `bitbar-web`, so I am using the global find and replace function of my IDE.
Buildkite concurrency group changes only.
Verified by peer review.
> Rationalise BitBar CI concurrency group

- packages/test-utilities/lib/in-memory-delivery.ts
The `InMemoryDelivery` we use in unit tests crashes when given an invalid payload as it always expects `payload.body.resourceSpans` to exist
This is mostly a safe assumption as TypeScript should ensure this is the case, but in a future PR we'll be reading a payload from a JSON file and that can cause invalid payloads to be sent to delivery
> Avoid crash in unit test delivery system when given an invalid payload

- packages/platforms/react-native/lib/retry-queue/directory.ts
- packages/platforms/react-native/tests/retry-queue/directory.test.ts
- packages/platforms/react-native/tests/utilities/file-system-fake.ts
This PR adds an abstraction over a directory for use with a new file-based retry queue to be added in a future PR
This is supported by a new fake implementation of `react-native-file-access` as the mock that ships with the library doesn't really deal with directories
The new `FileSystemFake` is implemented in 8919aaddacdac13fb15a4ea036554980d0a4261c, which is then consumed by the unit tests in the new `RetryQueueDirectory` in 202c62cb9c3fcce92a2768cc31cfa1074527bf9a
> Add `RetryQueueDirectory`

- CHANGELOG.md
- packages/platforms/browser/lib/auto-instrumentation/resource-load-plugin.ts
handle a known bug in certain browsers, where the `entryType` parameter should be optional in `PerformanceObserver.observe()`
https://bugs.webkit.org/show_bug.cgi?id=209216
> [PLAT-10765] Fix PerformanceObserver.entryTypes is required

- .buildkite/browser-pipeline.yml
Move Edge-latest testing to BrowserStack.
Moves Edge Latest browser tests to BrowserStack temporarily to avoid a bug on BitBar (due to be fixed next week).
Covered by CI.
> Move Edge-latest testing to BrowserStack

- CHANGELOG.md
- packages/platforms/react-native/lib/get-network-connection-type.ts
- packages/platforms/react-native/lib/span-attributes-source.ts
- packages/platforms/react-native/tests/span-attributes-source.test.ts
Add the `net.host.connection.subtype` string attribute when the `net.host.connection.type` has the value `cell`
Update unit tests to expect connection subtype attribute
> [PLAT-10863] Add new net.host.connection.subtype span attribute

- CHANGELOG.md
- packages/platforms/browser/lib/backgrounding-listener.ts
- packages/platforms/browser/lib/browser.ts
- packages/platforms/browser/tests/backgrounding-listener.test.ts
On some versions of Mobile Safari the `visibilitychange` event does not fire if a page is cached/suspended when navigating away, which can mean spans that should be discarded are left open.
This PR updates the backgrounding listener to also listen for `pagehide` and `pageshow` events which do fire in that scenario.
The backgrounding listener now tracks the current backgrounding state to avoid notifying subscribers more than once when both `visibilitychange` and `pageshow`/`pagehide` events are fired
> Listen for pagehide and pageshow events in backgrounding listener

- packages/platforms/react-native/lib/persistence/index.ts
- packages/platforms/react-native/lib/retry-queue/directory.ts
- packages/platforms/react-native/lib/retry-queue/file-based.ts
- packages/platforms/react-native/lib/retry-queue/index.ts
- packages/platforms/react-native/lib/retry-queue/timestamp-from-filename.ts
- packages/platforms/react-native/tests/retry-queue/file-based.test.ts
- packages/platforms/react-native/tests/retry-queue/index.test.ts
- packages/platforms/react-native/tests/retry-queue/timestamp-from-filename.test.ts
- packages/platforms/react-native/tsconfig.json
- packages/test-utilities/lib/create-payload.ts
- packages/test-utilities/lib/index.ts
This PR adds a file based retry queue that works by writing failed payloads to disk and reading from them when `flush` is called
If delivery is successful or fails with the `failure-discard` state, the file gets deleted. Otherwise the file is left on disk to be retried on the next `flush` call
Files are stored with a filename in the format `retry-<timestamp>-<span ID>.json` where `timestamp` is the largest `endTimeUnixNano` in the payload's spans
Any file with a timestamp more than 24 hours in the past or future will be deleted when `flush` is called. Files with invalid names (i.e. do not match the format) will also be deleted
This has only been unit tested so far so is not actually being used by the SDK yet
> Add file-based retry queue for React Native

- CHANGELOG.md
- packages/core/lib/clock.ts
- packages/core/tests/clock.test.ts
Browser timing APIs usually return a `DOMHighResTimestamp` (aka a double). These values are usually integers (i.e. whole milliseconds) but it is valid for them to contain a fractional part, representing nanoseconds
Currently we don’t do anything to handle this, which results in our encoded JSON payloads being invalid according to the OTEL spec
This PR updates the millisecond to nanosecond conversion to round nanoseconds to the nearest integer to ensure we always send a valid payload.
`performance.now` on React Native also returns a double, so went for implementing this in the core `millisecondsToNanoseconds` function as this is used to convert millisecond values by both of the platform-specific clocks
> Round timestamps to the nearest integer

- packages/platforms/react-native/__mocks__/@react-native-community/netinfo.ts
- packages/platforms/react-native/__mocks__/react-native.ts
- packages/platforms/react-native/lib/retry-queue/index.ts
- packages/platforms/react-native/tests/retry-queue/index.test.ts
Flush the retry queue in more situations on React Native — because there is a persistent queue, it makes sense to flush more often than in the browser SDK
Specifically the queue is flushed:
- when `BugsnagPerformance.start` is called
- when the app is backgrounded or foregrounded
- when the device gains network connectivity
> Flush the retry queue in more situations on React Native

- test/react-native/features/manual-spans.feature
- test/react-native/features/support/env.rb
This test is flakey and will be replaced as part of PLAT-11214 anyhow, so skipping for now
> Skip flakey React Native test for background spans

- packages/platforms/react-native/lib/id-generator.ts
On iOS the codegen for turbo modules doesn't run unless you run `pod install` with `RCT_NEW_ARCH_ENABLED=1`, and there are no compiler warnings or errors when the native module spec has changed - any new native methods added since the last codegen are just undefined at runtime.
We should therefore ensure the new native methods `requestEntropy` and `requestEntropyAsync` are present (as well as the native module itself) before using them.
> Check requestEntropy methods are present in native module

- test/browser/features/angular.feature
Fixes an Angular test flake on iOS - the angular test fixture renders a loading screen initially, and then lazy loads the app component that contains the elements. On some occasions the component hasn't loaded when we try to click the element, so the test now waits for the element to appear before clicking
> Fix flakey test: wait for element to appear in angular e2e tests

- CHANGELOG.md
- packages/platforms/browser/lib/browser.ts
- packages/platforms/browser/lib/default-routing-provider.ts
- packages/platforms/browser/lib/on-settle/index.ts
- packages/platforms/browser/tests/default-routing-provider.test.ts
- packages/platforms/browser/tests/on-settle/index.test.ts
Prevent the SDK from crashing when used in SSR frameworks such as Next or Nuxt. 
Currently `window` and `document` are accessed when the library is imported which causes a crash when the code is executed server-side as these are not defined.
This PR aims to prevent this and allow the SDK to be used in SSR apps, by exporting a noop client, onSettle and routing provider if `window` and `document` are undefined.
Added unit tests for the onSettle and routing provider noops, and tested manually with a Next.js app
> Export noops from browser package when window or document is undefined

- packages/react-navigation/lib/create-navigation-container.tsx
- packages/react-navigation/lib/navigation-context.tsx
- packages/react-navigation/lib/react-navigation-native-plugin.ts
- packages/react-navigation/rollup.config.mjs
Ensure navigation spans are not ended with time of `0` when not using a `CompleteNavigation` component
> Fix invalid span duration when ending immediately

- CHANGELOG.md
- packages/platforms/browser/lib/auto-instrumentation/page-load-phase-spans.ts
- packages/platforms/browser/lib/web-vitals.ts
- packages/platforms/browser/tests/web-vitals.test.ts
Prevent throwing an error in edge cases when `performance.getEntriesByType()` returns undefined
Add additional guard when getting entries for web vitals
Add unit test to ensure error is not thrown when `getEntriesByType` returns `undefined`
> [PLAT-11455] First input delay

- test/browser/features/lib/browser.rb
Update assertions for web vitals on [Firefox 122](https://www.mozilla.org/en-US/firefox/122.0/releasenotes/) to include [Largest Contentful Paint ](https://developer.mozilla.org/en-US/docs/Web/API/LargestContentfulPaint)
> Add LCP to firefox web vitals after version 122

- .buildkite/pipeline.yml
- packages/react-native-navigation/__tests__/react-native-navigation-plugin.test.ts
- packages/react-native-navigation/lib/react-native-navigation-plugin.ts
- test/react-native/features/fixtures/scenario-launcher/lib/ScenarioLauncher.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/react-native-navigation/ChangeRouteScenario.js
- test/react-native/features/react-native-navigation.feature
Automatically instrument navigation spans when using `react-native-navigation`
Add event listeners to the `Navigation` library to start and automatically end a navigation span when the route changes
**Note:** this approach also creates a navigation span for the initial route due to the way the end to end test is instrumented
- Add event listeners to plugin
- Add navigation span attributes
- Update unit tests to check that a span in automatically started on route change
- Update end to end tests to check that a span is automatically started on a route change
> [PLAT-11566] Instrument navigation spans

- .buildkite/pipeline.yml
- jest.config.js
- package-lock.json
- packages/react-native-navigation/__mocks__/@bugsnag/react-native-performance.ts
- packages/react-native-navigation/__mocks__/react-native-navigation.ts
- packages/react-native-navigation/__tests__/CompleteNavigation.test.tsx
- packages/react-native-navigation/__tests__/react-native-navigation-plugin.test.ts
- packages/react-native-navigation/lib/CompleteNavigation.tsx
- packages/react-native-navigation/lib/index.ts
- packages/react-native-navigation/lib/react-native-navigation-plugin.ts
- packages/react-native-navigation/package.json
- packages/react-native-navigation/rollup.config.mjs
- test/react-native/features/fixtures/scenario-launcher/scenarios/react-native-navigation/ChangeRouteScenario.js
- test/react-native/features/react-native-navigation.feature
Add `CompleteNavigation` component to make navigation spans more accurate 
Same pattern for component lifecycle methods as the `@bugsnag/react-navigation` plugin component, but leveraging the `getPlugin` method from `BugsnagPerformance` as we are not able to provide a wrapper component and leverage context to have a single point of reference for number of mounted components and the state of the current navigation span
- Added new component
- Updated plugin implementation to end spans depending on the number of components waiting
- Added `bugsnag.navigation.ended_by` span attribute
- Unit tests for the NavigationComplete component
- Unit test that the plugin handles awaiting components and updating span attributes correctly
- Update end to end test to instrument `NavigationComplete` …
> [PLAT-11567] Complete navigation component

- .buildkite/pipeline.yml
- packages/platforms/react-native/lib/auto-instrumentation/app-start-plugin.tsx
- test/react-native/features/fixtures/scenario-launcher/scenarios/ReactNativeNavigationScenario.js
- test/react-native/features/react-native-navigation.feature
Ensure AppStart spans are instrumented when using `react-native-navigation`
Updated end to end test fixture and assertions
> [PLAT-11721] Test app start spans with react-native-navigation

- packages/react-native-navigation/__tests__/react-native-navigation-plugin.test.ts
- packages/react-native-navigation/lib/react-native-navigation-plugin.ts
- packages/react-navigation/lib/navigation-context.tsx
- packages/react-navigation/test/navigation-context.test.tsx
- test/react-native/features/fixtures/scenario-launcher/scenarios/ReactNavigationScenario.js
- test/react-native/features/react-navigation.feature
Add the `bugsnag.navigation.previous_route` span attribute
Update unit tests and end to end tests to ensure the previous route is handled with the `@react-navigation/native` and `react-native-navigation` plugins
> [PLAT-11722] Previous route span attribute

- CHANGELOG.md
- package-lock.json
- packages/react-native-navigation/package.json
Prevent all packages from being re-released during build process due to [package version inconsistency](https://lerna.js.org/docs/features/version-and-publish#fixedlocked-mode-default) 
> Note: If you have a major version zero, all updates are [considered breaking](https://semver.org/#spec-item-4). Because of that, running lerna publish with a major version zero and choosing any non-prerelease version number will cause new versions to be published for all packages, even if not all packages have changed since the last release.
> Fixup release 2.3.0

- bin/release.sh
- `--dist-tag` is not a valid option for `version`, it needs to be passed to `publish`
- update the release script to pass `--dist-tag next` when publishing prereleases
- performed a `2.3.0-alpha.0` of the `trace-propagation` branch using the updated script
> pass --dist-tag next to publish

- CHANGELOG.md
- packages/core/lib/batch-processor.ts
- packages/core/lib/config.ts
- packages/core/lib/probability-manager.ts
- packages/core/tests/batch-processor.test.ts
- packages/platforms/browser/tests/__mocks__/@bugsnag/delivery-fetch-performance.ts
- packages/platforms/browser/tests/browser.test.ts
This PR ensures that the correct sampling rate is used for a batch which is filled before the initial sampling request has been made by delaying batching while the request is in flight.
The config option for `samplingProbability` has also been removed.
Add integration test for browser client which awaits the initial sampling request when a full batch is created before starting bugsnag
> [PLAT-11800] Delay initial span batching

- CHANGELOG.md
- packages/request-tracker/lib/request-tracker-fetch.ts
- packages/request-tracker/tests/request-tracker-fetch.test.ts
- test/browser/features/fixtures/packages/traceparent/index.html
- test/browser/features/fixtures/packages/traceparent/src/index.js
- test/browser/features/traceparent.feature
Fixes a bug in the fetch request tracker where any headers that are set in a `Request` object passed to `fetch` were not being preserved. Similarly if headers are set using the `Headers` class in the request options these would also be wiped.
This is because trace propagation headers were always being merged with the options object (the second argument passed to fetch) as an object literal, however request headers can be set in a few different ways:
- As an object literal in options
- As a `Headers` instance in options
- In a `Request` object passed as the first argument to `fetch`
The behaviour of `fetch` is such that if headers are set in the options object these will take precedence, and any headers defined in a `Request` object are ignored.
Reworked the `mergeRequestHeaders` logic to …
> Ensure existing headers are preserved for fetch requests

- packages/platforms/react-native/lib/auto-instrumentation/network-request-plugin.ts
- packages/platforms/react-native/lib/client.ts
- packages/platforms/react-native/tests/auto-instrumentation/network-request-plugin.test.ts
- test/react-native/features/fixtures/scenario-launcher/lib/ScenarioContext.js
- test/react-native/features/fixtures/scenario-launcher/lib/ScenarioLauncher.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/TracePropagationScenario.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/index.js
- test/react-native/features/traceparent.feature
Set the `traceparent` header on intercepted network requests in React Native
Follows the same approach as the existing browser implementation
Added unit and e2e tests. 
Introduced the concept of a `ScenarioContext` in the RN test fixture to allow data to be passed down into scenario components (in this case the reflect endpoint)
> Add trace propagation headers for React Native

- .buildkite/react-native-pipeline.full.yml
- test/react-native/features/fixtures/scenario-launcher/scenarios/TracePropagationScenario.js
- test/react-native/features/traceparent.feature
Some of the RN test fixture build began failing because they were still using node 16 and the RN CLI now requires node 18. This PR bumps the node version to 18 for all RN test fixture builds.
Also fixed a test flake in the trace propagation e2e tests due to span batches sometimes being larger than expected.
> Bump node to 18 for all RN test fixture builds and fix test flakes

- CHANGELOG.md
- packages/platforms/browser/lib/auto-instrumentation/network-request-plugin.ts
- packages/platforms/browser/tests/browser.test.ts
- packages/platforms/react-native/lib/auto-instrumentation/network-request-plugin.ts
- packages/platforms/react-native/lib/config.ts
- packages/platforms/react-native/tests/auto-instrumentation/network-request-plugin.test.ts
- packages/platforms/react-native/tests/config.test.ts
- packages/request-tracker/lib/network-request-callback.ts
- test/react-native/features/fixtures/scenario-launcher/scenarios/TracePropagationScenario.js
Replaces the `propagateTraceContext` boolean in the network request callback with a new config option `tracePropagationUrls` (an array of RegExp's or strings) to control which requests get propagation headers (in React Native only). 
`tracePropagationUrls` is an array of RegExp's or strings (similar to `settleIgnoreUrls` in the browser package)
`propagateTraceContext` has been removed from the base `NetworkRequestInfo` interface in the request-tracker package and added to `BrowserNetworkRequestInfo` instead.
Updated the unit and e2e tests
> Add `tracePropagationUrls` config option for React Native

- CHANGELOG.md
- package-lock.json
- packages/core/lib/persistence.ts
- packages/core/package.json
- packages/platforms/browser/package.json
- packages/platforms/react-native/lib/persistence/file-based.ts
- packages/platforms/react-native/package.json
Fixes the following error when using esm in node: Named export 'isCuid' not found. The requested module '@bugsnag/cuid' is a CommonJS module, which may not support all module.exports as named exports. CommonJS modules can always be imported via the default export
- Reproduced the error using a "qwik" project as reported by one of our customers. Then made the same changes manually to the files in node_modules to verify the error is resolved
> fix cuid imports

- CHANGELOG.md
- packages/core/lib/core.ts
- packages/core/lib/network-span.ts
- packages/core/lib/span-factory.ts
- packages/core/tests/core.test.ts
- packages/platforms/browser/lib/auto-instrumentation/network-request-plugin.ts
- packages/platforms/browser/tests/auto-instrumentation/network-request-plugin.test.ts
- packages/platforms/react-native/lib/auto-instrumentation/network-request-plugin.ts
- packages/platforms/react-native/tests/auto-instrumentation/network-request-plugin.test.ts
- packages/test-utilities/lib/mock-span-factory.ts
- test/browser/features/fixtures/packages/manual-span/index.html
- test/browser/features/fixtures/packages/manual-span/src/index.js
- test/browser/features/network-spans.feature
- test/browser/features/traceparent.feature
- test/react-native/features/network-spans.feature
add a new `startNetworkSpan` method to the core client
update network span naming convention to `[HTTP/VERB]`
Add unit test for `startNetworkSpan` and attributes
> [PLAT-11983] Manual network span API

- dockerfiles/Dockerfile.license-finder
Ensure that the license-finder docker image has the required packages needed to work on CI.
covered by CI
> Fix missing ruby packages from the license-finder docker image

- package-lock.json
- package.json
Resolve CVE-2023-49293, CVE-2024-23331 and CVE-2024-31207 by overriding the version of `vite` used by `@angular-devkit/build-angular`, which is unable to be patched using `npm update` due to strict dependencies in the `@angular-devkit/build-angular` package
> [PLAT-11470] update vite to 4.5.3

- package-lock.json
- package.json
Resolve CVE-2024-29180 by overriding `webpack-dev-middleware` to `v7.1.0` (required by `@angular-devkit/build-angular`)
> [PLAT-11825] Update webpack-dev-middleware

- CHANGELOG.md
- packages/plugin-react-navigation/lib/navigation-context.tsx
- packages/plugin-react-navigation/test/create-navigation-container.test.tsx
- packages/plugin-react-navigation/test/navigation-context.test.tsx
Fix an issue where a span ended without a NavigationComplete component would inherit the end time of the last span ended via the NavigationComplete component
As an aside, the plugin now directly uses `performance.now` for start time, as per end time. 
Added unit test to ensure navigation spans do not inherit the last render time from the `NavigationComplete` component
> [PLAT-12196] Clear lastRenderTime after ending navigation span

- .buildkite/react-native-pipeline.full.yml
Move the 'full' react native CI pipeline to MacOS 14/Java 17 (required for React Native 0.73) - this was missed in #464 when 0.73 tests were moved from the basic to full pipeline.
covered by a full CI run
> Move 'full' React Native pipeline to MacOS 14 / Java 17

- test/react-native/features/fixtures/scenario-launcher/lib/Persistence.js
Ensure the test fixture clears the file-based retry queue between scenarios.
This was causing a test flake in the retry test where stored traces that failed to send from previous scenarios were sometimes being sent in the next scenario, presumably because the app was being restarted before the files could be deleted
covered by CI
> test(react-native): clear retry queue between scenarios

- package-lock.json
- packages/core/lib/config.ts
- packages/core/lib/core.ts
- packages/platforms/browser/lib/config.ts
- packages/platforms/browser/package.json
- packages/platforms/browser/tests/browser.test.ts
- packages/plugin-react-navigation/lib/create-navigation-container.tsx
Implement error correlation for browser performance
Call `addOnError` from bugsnag notifier when provided as a configuration option
Added new `bugsnag` configuration option to core client
Added unit tests for adding span and trace id to a reported error
> [PLAT-12231] Browser error correlation

- CHANGELOG.md
- packages/platforms/react-native/lib/client.ts
- packages/platforms/react-native/lib/clock.ts
- packages/platforms/react-native/lib/id-generator.ts
- packages/platforms/react-native/tests/id-generator.test.ts
Support remote debugging via Chrome for React Native apps. 
Updates the React Native client to avoid making synchronous native calls if we detect that remote debugging is enabled (see #370).
Currently there are only two synchronous native calls made, both during initialisation, to `getDeviceInfo` (to get native device metadata( and `requestEntropy` to (initialise the entropy source for the id generator).
If remote debugging is detected we simply don't make these calls - this means that when running in the debugger some device-related resource attributes will be missing from resource spans, and the id generator will fall back to using a JS entropy source, but the client should otherwise work as expected.
Tested manually with the remote debugger
> feat(react-native): support remote debugging in chrome

- CHANGELOG.md
- packages/plugin-react-navigation/lib/create-navigation-container.tsx
Support navigation refs created using `useRef`.
Currently the React Navigation plugin expects the passed in navigation ref to be created with `useNavigationContainerRef`, and crashes if the ref was created with `useRef`, since in that case `getCurrentRoute` should be accessed via `ref.current`.
the code now first checks if `ref.current` exists and then falls back to calling `getCurrentRoute` on the ref directly.
> Fix crash when navigation ref is created with useRef

- .buildkite/browser-pipeline.yml
- .buildkite/react-native-navigation-pipeline.full.yml
- .buildkite/react-native-navigation-pipeline.yml
- .buildkite/react-native-pipeline.full.yml
- .buildkite/react-native-pipeline.yml
Ensure the Bitbar tests run using appium v1.22
Covered by CI
> [PLAT-12480] Add appium v1.22 to the tests run on Bitbar

- CHANGELOG.md
- packages/core/lib/attributes.ts
- packages/core/tests/delivery.test.ts
- packages/platforms/browser/lib/config.ts
- packages/platforms/browser/lib/resource-attributes-source.ts
- packages/platforms/browser/tests/config.test.ts
- packages/platforms/browser/tests/resource-attributes-source.test.ts
- packages/platforms/react-native/lib/resource-attributes-source.ts
- packages/test-utilities/lib/create-configuration.ts
- packages/test-utilities/lib/resource-attributes-source.ts
- test/browser/features/fixtures/packages/manual-span/src/index.js
- test/browser/features/manual-spans.feature
- Adds `service.name` as a core resource attribute
- Adds a new `serviceName` config option for the browser to allow users to configure this
- Ensures the `service.name` attribute is always set on all platforms
Added `service.name` to the core resource attribute class to ensure that it is set on all platforms (as it's a required attribute in the OTEL spec)
Previously this attribute was not being set on the browser package, so a new config option has been added for browser with a default value of `unknown_service`.
On React Native, service.name is set from the bundle identifier - this has been updated to fall back to `unknown_service` if native device info is unavailable for any reason.
> Add serviceName config option for browser and ensure service.name attribute is always set

- CHANGELOG.md
- packages/vue-router/lib/vue-router-routing-provider.ts
- packages/vue-router/package.json
- packages/vue-router/tests/vue-router-routing-provider.test.ts
- test/browser/features/fixtures/packages/vue-router/src/App.vue
- test/browser/features/fixtures/packages/vue-router/src/main.js
- test/browser/features/fixtures/packages/vue-router/src/views/ContactProfile.vue
- test/browser/features/fixtures/packages/vue-router/src/views/ContactView.vue
- test/browser/features/vue-router.feature
Replace the usage of `path-to-regexp` and use Vue's `router.resolve` to resolve routes in `VueRoutingProvider`.
Fixes an issue where routes with parantheses (generated by nuxt) were failing to resolve (see #460)
v4 of `vue-router` (which we depend on) no longer uses `path-to-regexp` internally to parse routes, and now uses its own parsing system that supports dynamic routing. 
The router object has a `resolve` method that seems to do what we need (find a corresponding route from a given URL) - and also removes the need to flatten routes when resolving.
- Removed path-to-regexp dependency
- Updated resolveRoute to use Vue's router.resolve
- Updated e2e tests to test nested routes and routes with parentheses
Updated the e2e tests to include a nested route and a route with parentheses
> feat(vue-router): use vue router to resolve routes

- CHANGELOG.md
- packages/core/lib/config.ts
- packages/core/lib/core.ts
- packages/platforms/browser/tests/browser.test.ts
Refactor the error correlation implementation by patching the `_notify` method instead of leveraging `addOnError` to ensure callbacks run before the current span has closed
> [PLAT-12475] Monkey patch notify method 

- CHANGELOG.md
- packages/platforms/react-native/BugsnagReactNativePerformance.podspec
- packages/platforms/react-native/android/build.gradle
- packages/platforms/react-native/android/src/main/AndroidManifest.xml
- packages/platforms/react-native/android/src/main/java/com/bugsnag/android/performance/NativeBugsnagPerformanceImpl.java
- packages/platforms/react-native/android/src/newarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
- packages/platforms/react-native/android/src/newarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformancePackage.java
- packages/platforms/react-native/android/src/oldarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
- packages/platforms/react-native/android/src/oldarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformancePackage.java
- packages/platforms/react-native/ios/BugsnagReactNativePerformance.xcodeproj/project.pbxproj
- packages/platforms/react-native/lib/native.ts
Refactors the native module in the React Native package to ensure full backwards compatibility with the Old Architecture.
- Android codebase has been updated so that the New Architecture types are not compiled when not available. 
- iOS podspec has been updated to ensure the correct dependencies are installed on Old Architecture.
- `native.ts` has been updated to load the native module from the old NativeModules API if turbo modules are not enabled. 
> React Native: Ensure native module is fully backwards compatible

- package-lock.json
- packages/platforms/react-native/lib/persistence/file-utils.ts
- packages/platforms/react-native/lib/persistence/file.ts
- packages/platforms/react-native/package.json
Adds support for older versions of react-native-file-access:
- Loosens the peer dependency version requirements to <=1.7.1 (latest version that supports RN 0.64)
- Vendor the file utility functions that were added in v2.3.0 of react-native-file-access to ensure backwards compatibility
Relied on existing tests
> feat(react-native): support react-native-file-access v1.x

- packages/core/lib/batch-processor.ts
- packages/core/lib/core.ts
- packages/core/lib/probability-manager.ts
- packages/core/tests/batch-processor.test.ts
- packages/core/tests/core.test.ts
- packages/core/tests/probability-manager.test.ts
- packages/platforms/browser/tests/browser.test.ts
Currently we set long running timers when the `ProbabilityManager` is created or when a probability value is set in order to ensure we check for a fresh probability value at least once a day. This is necessary because if the probability is set to 0 by the server then this is the only mechanism that will eventually reset the probability to a non-zero value
The current design leads to a warning on some versions of React Native because there are possible correctness concerns — the timers aren't triggered in the background and so won't fire until the app returns to the foreground. For our purposes this is fine, but we can avoid the warning with a small refactor
This PR replaces the current `setTimeout` mechanism with a new `ProbabilityManager#ensureFreshProbability` method. This method can be …
> Avoid long running timers when ensuring probability freshness

- .buildkite/react-native-pipeline.yml
- bin/generate-react-native-fixture
- packages/platforms/react-native/lib/auto-instrumentation/app-start-plugin.tsx
- packages/plugin-react-navigation/lib/complete-navigation.tsx
- test/react-native/features/fixtures/app/App.js
- test/react-native/features/fixtures/app/android/AndroidManifest.xml
- test/react-native/features/fixtures/app/android/MainActivity.0.64.java
- test/react-native/features/fixtures/scenario-launcher/lib/ScenarioLauncher.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/AppStartScenario.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/WrapperComponentProviderScenario.js
Adds React Native 0.64 tests to CI, and fixes a few minor issues found during testing
- Updated the test fixture generation script to allow generating a working 0.64 test fixture:
- Ensures compatible versions of peer dependencies are installed
- Makes some modifications to the generated project to fix various build issues (see `configureRN064Fixture`)
- Updated the scenario-launcher package to support RN 0.64
- Tries to use `unstable_RootTagContext` if `RootTagContext` is unavailable (this changed in 0.65)
- Adds a React import to scenarios that were missing it
- Added a React import to the app start plugin
- Fixed a render error in the `CompleteNavigation` component for `plugin-react-navigation` 
> React Native 0.64 support

- packages/platforms/react-native/lib/retry-queue/directory.ts
- packages/platforms/react-native/lib/retry-queue/file-based.ts
- packages/platforms/react-native/lib/retry-queue/timestamp-from-filename.ts
- packages/platforms/react-native/tests/retry-queue/directory.test.ts
- packages/platforms/react-native/tests/retry-queue/file-based.test.ts
- packages/platforms/react-native/tests/retry-queue/index.test.ts
- packages/platforms/react-native/tests/retry-queue/timestamp-from-filename.test.ts
Replace usage of BigInt in the react native retry queue as this isn't supported on older versions of React Native (or more specifically on older versions of Hermes).
Instead of using nanosecond timestamps based on the largest span end time in the payload, the retry queue now uses the time the payload was added to the queue (in ms) for the filename. This is already being passed to `FileBasedRetryQueue#add` by the batch processor, but was previously an unused parameter.
Although it shouldn't really be possible for two files to be created with the same timestamp (as the time is recorded when a batch is flushed and a failed batch is only ever added to the retry queue once), the span ID of the last span in the payload is still used in the filename to ensure filenames are unique.
This also …
> refactor(react-native): use batch time for filenames in retry queue

- examples/react-navigation/android-fragments/package-lock.json
- examples/rn072/yarn.lock
- package-lock.json
- package.json
- packages/plugin-react-native-navigation/babel.config.cjs
- packages/plugin-react-navigation/babel.config.cjs
Reduce the number of security warnings.
When I updated the lock files, the tests broke. In order to fix them, I had to add a development dependency on `metro-react-native-babel-preset` as well as `@babel/plugin-transform-private-methods`.
I also had to enable that private methods function as part of the tests. Presumably this was standard for tests previously but is now opt in.
> Update the package lock file

- .buildkite/react-native-pipeline.full.yml
- bin/generate-react-native-fixture
- packages/platforms/react-native/lib/auto-instrumentation/app-start-plugin.tsx
- packages/plugin-react-navigation/lib/complete-navigation.tsx
- test/react-native/features/fixtures/app/App.js
- test/react-native/features/fixtures/app/android/AndroidManifest.xml
- test/react-native/features/fixtures/app/android/MainActivity.0.64.java
- test/react-native/features/fixtures/scenario-launcher/lib/ScenarioLauncher.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/AppStartScenario.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/WrapperComponentProviderScenario.js
Adds React Native 0.64 tests to CI, and fixes a few minor issues found during testing. 
Changes have been cherry picked from https://github.com/bugsnag/bugsnag-js-performance/pull/483, with a couple of small tweaks:
-  0.64 tests now run as part of the 'full' CI pipeline
- Fixed some versions of react navigation dependencies in the test fixture generation script that were missed
> Add React Native 0.64 support

- CHANGELOG.md
- packages/platforms/react-native/lib/backgrounding-listener.ts
- packages/platforms/react-native/tests/backgrounding-listener.test.ts
In React Native 0.74+, when an iOS app launches the initial `AppStateStatus` changed from `unknown` to `inactive`. This wasn't being accounted for in the backgrounding listener, so the initial background state was incorrectly being set to `in-background`. 
This PR updates the React Native backgrounding listener so that the app is considered in foreground on launch unless the initial app state is `background`.
When the backgrounding listener is created the initial app state is now only set to `in-background` if the initial app state status is explicitly `background` - any other initial state (`active`, `inactive`, or `unknown`) is considered `in-foreground`  until an app state change event occurs.
Covered by unit tests and manual testing.
The current structure of the end-to-end test …
> Set initial background state to foreground if initial app state is 'inactive'

- packages/platforms/browser/lib/auto-instrumentation/network-request-plugin.ts
- packages/platforms/browser/tests/auto-instrumentation/network-request-plugin.test.ts
- test/browser/features/trace-propagation.feature
The JS SDK uses 32 bit values for p & r because JS numbers cannot hold 64 bit integers
We need to be able to determine if an r value is 32 or 64 bit in order to consume the tracestate correctly, so we're now using explicit bit sizes in the r value key (i.e. r32 & r64)
> Use 'r32' as the r value key in tracestate

- .buildkite/react-native-pipeline.full.yml
- .buildkite/react-native-pipeline.yml
- bin/generate-react-native-fixture
- test/react-native/features/error-correlation.feature
- test/react-native/features/fixtures/app/android/MainActivity.0.75.kt
- test/react-native/features/fixtures/app/babel.config.js
- test/react-native/features/fixtures/scenario-launcher/ScenarioLauncher.podspec
- test/react-native/features/fixtures/scenario-launcher/ios/ScenarioLauncher.xcodeproj/project.pbxproj
Adds React Native 0.75 tests to the CI pipeline.
Also fixes the following issues with React Native test fixtures and e2e tests:
- Add pbxproj file and fix podspec in scenario launcher package (required for native iOS modules on older versions of React Native)
- Fix Android gradle file replacements for RN 0.64 (Flipper was not being fully removed, causing build issues on some CI machines and in local dev)
- Modify babel.config.js in test fixtures instead of replacing the whole file (Adds the required babel plugins while preserving the existing as this varies between react native versions)
- Fix typos in error correlation feature file
> Add React Native 0.75 to test matrix

- CHANGELOG.md
- packages/core/lib/span-factory.ts
- packages/core/lib/span.ts
- packages/core/tests/span-context.test.ts
- packages/core/tests/span.test.ts
- packages/platforms/browser/tests/auto-instrumentation/route-change-plugin.test.ts
- packages/platforms/browser/tests/span-attributes-source.test.ts
Mitigates the potential for memory leaks caused by failing to end a span.
Currently if a span on the context stack is not ended for any reason (e.g. a developer has a problem with their logic for closing spans), then the span will remain open and there will be a reference to the span in the context stack until the thread / process / document (depending on platform) is killed.
Ideally we would use `WeakRef`s in the context stack to allow spans on the context stack to be garbage collected, however as `WeakRef` isn't supported on older browser versions we need an alternative approach.
So to avoid holding references indefinitely, any spans with a start time older than 1 hour are considered 'invalid', allowing them to be removed from the context stack naturally (since invalid spans are popped …
> Discard spans open for more than one hour

- CHANGELOG.md
- packages/core/lib/span-factory.ts
- packages/core/lib/span.ts
- packages/core/tests/span.test.ts
- packages/platforms/browser/lib/auto-instrumentation/route-change-plugin.ts
Support custom attributes
- Expose setAttribute method in the public span API
- Add span name validation
Add unit test to ensure setAttribute adds attributes as necessary
> [PLAT-12634] Make setAttribute public

- CHANGELOG.md
- packages/core/lib/core.ts
- packages/core/tests/core.test.ts
- packages/platforms/browser/tests/on-settle/index.test.ts
> The SaaS span endpoint now supports the format <project_api_key>.otlp.bugsnag.com
> This should just be the default value for the endpoint – if the developer passes their own URL we just use that value directly (don’t attempt to inject the API key into the provided URL).
Mutate the configuration so that the actual value used is available to all consumers of the configuration, such as request instrumentations which use the value to determine which requests should be tracked or not, and what URLs to ignore in request settling.
- use API key subdomain as default endpoint
Note: e2e tests not added the depend on using a custom endpoint, which prevents us from testing this functionality at the e2e level
> use API key subdomain as default endpoint

- CHANGELOG.md
- lerna.json
- package-lock.json
- packages/core/package.json
- packages/delivery-fetch/package.json
- packages/platforms/browser/package.json
- packages/platforms/react-native/lib/auto-instrumentation/app-start-plugin.tsx
- packages/platforms/react-native/lib/client.ts
- packages/platforms/react-native/lib/create-app-start-span.ts
- packages/platforms/react-native/lib/platform-extensions.tsx
- packages/platforms/react-native/lib/use-end-span-on-mount.ts
- packages/platforms/react-native/package.json
- packages/platforms/react-native/tests/platform-extensions.test.ts
- packages/plugin-react-native-navigation/package.json
- packages/plugin-react-navigation/package.json
- packages/request-tracker/package.json
- test/react-native/features/app-start-spans.feature
- test/react-native/features/fixtures/scenario-launcher/package.json
- test/react-native/features/fixtures/scenario-launcher/scenarios/AppStartWrapperScenario.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/index.js
Provide an alternative method to instrument app start spans aside from `setWrapperComponentProvider`
Using a higher order component (HOC) will prevent the app from re-rendering when root props are updated from the native side
- Expose new `withInstrumentedAppStarts` wrapper method from the performance client
- This PR also includes an alpha release for testing purposes
- Add new end to end test to validate spans are still created using the new method
- Manual testing that the root app does not re-render when properties update from native iOS code
> [PLAT-12625] Create new app start span wrapper

- packages/core/lib/attributes.ts
- packages/core/lib/batch-processor.ts
- packages/core/lib/config.ts
- packages/core/lib/core.ts
- packages/core/lib/custom-attribute-limits.ts
- packages/core/lib/span-factory.ts
- packages/core/lib/span.ts
- packages/core/tests/attributes.test.ts
- packages/core/tests/span.test.ts
- packages/platforms/browser/lib/auto-instrumentation/route-change-plugin.ts
- packages/platforms/browser/tests/span-attributes-source.test.ts
- packages/test-utilities/lib/create-span-attributes.ts
- packages/test-utilities/lib/create-span.ts
- packages/test-utilities/lib/index.ts
Add validation for custom span attributes
- Add new configuration options for attribute validation
- Add new validation method for truncating string and array attributes based on configuration options
- Add new validation method for dropping spans based on configuration options
- Add logging for modified spans
Add unit tests for all attribute limits and behaviours
> Custom attribute limits

- bin/generate-react-native-fixture
Updates the test fixture script to use the latest version of react-native-file-access and removes the static frameworks workaround for RN 0.75 tests.
Previously static frameworks were required for iOS in React Native 0.75 in order to work around an issue in react-native-file-access - this issue has now been [fixed](https://github.com/alpha0010/react-native-file-access/pull/88) in v3.1.1 of react-native-file-access, so the workaround is no longer required.
Relied on CI
> test(react-native): bump react-native-file-access version and remove workaround

- test/react-native/features/fixtures/scenario-launcher/lib/CommandRunner.js
- test/react-native/features/fixtures/scenario-launcher/lib/ScenarioLauncher.js
- test/react-native/features/steps/react-native-steps.rb
Make react-native maze-runner command pattern idempotent 
- Store the last command uuid
- Add the last command uuid to the next command request
- Remove timeout message `Test fixture did not GET /command`
> Idempotent test commands in React Native

- docker-compose.yml
Fix the following overnight failures building the Maze Runner image:
```
Failed to load /var/lib/buildkite-agent/builds/docker_env_file: open /var/lib/buildkite-agent/builds/docker_env_file: no such file or directory
```
It's unclear how the failures started (why best guess is an S3 secrets change), but we don't actually provide a Docker env file anyway and so this complexity can just be removed.
Covered by a full CI run.
> Remove CI pipeline Docker env files

- .buildkite/react-native-pipeline.yml
- bin/generate-react-native-fixture
- docker-compose.yml
- test/react-native/features/fixtures/scenario-launcher/ScenarioLauncher.podspec
- test/react-native/features/fixtures/scenario-launcher/android/build.gradle
- test/react-native/features/fixtures/scenario-launcher/android/src/main/java/com/bugsnag/reactnative/scenariolauncher/ScenarioLauncherImpl.java
- test/react-native/features/fixtures/scenario-launcher/android/src/newarch/java/com/bugsnag/reactnative/scenariolauncher/ScenarioLauncher.java
- test/react-native/features/fixtures/scenario-launcher/android/src/oldarch/java/com/bugsnag/reactnative/scenariolauncher/ScenarioLauncher.java
- test/react-native/features/fixtures/scenario-launcher/ios/ScenarioLauncher.h
- test/react-native/features/fixtures/scenario-launcher/ios/ScenarioLauncher.mm
- test/react-native/features/fixtures/scenario-launcher/lib/NativeScenarioLauncher.ts
- test/react-native/features/fixtures/scenario-launcher/scenarios/NativeIntegrationScenario.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/index.js
- test/react-native/features/native-integration.feature
- test/react-native/features/support/env.rb
e2e test setup for native performance integration in React Native:
- Generate a separate e2e test fixture with native performance SDKs installed.
- Add support for starting the native Android and Cocoa SDKs through the scenario launcher
- Add a basic scenario that sends a custom native span - this is really a placeholder test to make sure that the setup works and will be replaced when we start to add functionality.
A separate test fixture is required so that we can make sure the SDK continues to work as expected when native Android and Cocoa performance SDKs are not installed (existing fixtures and tests).
The test fixture generation script will only install the native Android and Cocoa SDKs when the `NATIVE_INTEGRATION` environment variable is set.
Covered by CI
> RN native integration e2e test setup

- bin/generate-react-native-fixture
- test/react-native/features/fixtures/app/Gemfile
Fix the React Native CI pipeline:
- Pin the xcodeproj gem version in generated test fixtures - for RN 0.64 this requires a gemfile to be added to the generated fixture.
- Run `bundle install && bundle exec pod install` in test fixtures to use the correct version of cocoapods for each fixture
> Fix React Native CI

- packages/platforms/react-native/__mocks__/react-native.ts
- packages/platforms/react-native/android/src/main/java/com/bugsnag/android/performance/NativeBugsnagPerformanceImpl.java
- packages/platforms/react-native/android/src/newarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
- packages/platforms/react-native/android/src/oldarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
- packages/platforms/react-native/ios/BugsnagCocoaPerformanceFromBugsnagReactNativePerformance.h
- packages/platforms/react-native/ios/BugsnagCocoaPerformanceFromBugsnagReactNativePerformance.m
- packages/platforms/react-native/ios/BugsnagPerformanceConfiguration.h
- packages/platforms/react-native/ios/BugsnagReactNativePerformance.mm
- packages/platforms/react-native/ios/BugsnagReactNativePerformance.xcodeproj/project.pbxproj
- packages/platforms/react-native/lib/NativeBugsnagPerformance.ts
Adds the basic bridge to the Cocoa Performance Crosstalk API and a new Turbo Module method to check at runtime if the native Android/Cocoa Performance SDK is available
Covered by existing CI as it's not used anywhere yet.
> feat(react-native): discover native performance SDKs

- bin/generate-react-native-fixture
- packages/platforms/react-native/__mocks__/react-native.ts
- packages/platforms/react-native/android/build.gradle
- packages/platforms/react-native/android/src/main/java/com/bugsnag/android/performance/NativeBugsnagPerformanceImpl.java
- packages/platforms/react-native/android/src/newarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
- packages/platforms/react-native/android/src/oldarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
- packages/platforms/react-native/ios/BugsnagReactNativePerformance.mm
- packages/platforms/react-native/lib/NativeBugsnagPerformance.ts
- packages/platforms/react-native/lib/client.ts
- packages/platforms/react-native/lib/config.ts
- packages/platforms/react-native/lib/index.ts
- packages/platforms/react-native/lib/platform-extensions.tsx
- packages/platforms/react-native/tests/client.test.ts
- test/react-native/features/fixtures/scenario-launcher/android/build.gradle
- test/react-native/features/fixtures/scenario-launcher/android/src/main/java/com/bugsnag/reactnative/scenariolauncher/ScenarioLauncherImpl.java
- test/react-native/features/fixtures/scenario-launcher/ios/ScenarioLauncher.mm
- test/react-native/features/fixtures/scenario-launcher/lib/ScenarioLauncher.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/NativeIntegrationScenario.js
- test/react-native/features/native-integration.feature
Adds a new `BugsnagPerformance.attach` method to React Native Performance to allow attaching to an already running native (Android or Cocoa) performance SDK.
This is effectively a wrapper around `BugsnagPerformance.start` that loads the native configuration and uses this to start the native SDK
Added a new method `getNativeConfiguration` to the Turbo Module, which returns the finalised configuration passed to native `start` or `null` if the native SDK has not been started.
When `attach` is called, the native config is merged with JS-specific config passed to `attach` before calling `start`
`BugsnagPerformance.attach` will log a warning and noop if the native SDK is not installed or has not been started.
- Added new unit tests for attach
- Updated the e2e tests to check that the React …
> Add support for attaching to native performance SDKs

- test/browser/features/angular.feature
- test/browser/features/fixtures/packages/react-router/src/index.jsx
- test/browser/features/fixtures/packages/vue-router/src/main.js
- test/browser/features/react-router.feature
- test/browser/features/vue-router.feature
Disables full page load instrumentation for react and vue router e2e tests.
Also updates the scenarios so that they have unique names in CI. This makes it easier to see what has failed and stops buildkite overwriting the artifacts if more than one have failed on the same run.
These tests were failing on Safari 11 - primarily because the batch timeout is set to 5 seconds and the safari test seems to run very slowly, clicking on the navigation almost 10 seconds after navigating to the URL, so the trace is sent before the navigation happens.
Because we don't get PageLoadPhase spans on Safari 11 the number of spans sent is much less, making the test setup awkward. We could fix this by increasing the batch timeout but that will slow all the tests down, and since the page load spans aren't …
> test(browser): disable full page loads for react and vue router tests

- CHANGELOG.md
- packages/platforms/react-native/lib/create-app-start-span.ts
- packages/platforms/react-native/tests/create-app-start-span.test.ts
Fixes a bug in `createAppStartSpan` where a duplicate app start span was being started
Added some unit tests around `createAppStartSpan`
> fix(react-native): prevent duplicate app start spans from being started

- bin/generate-react-native-fixture
Pins the version of react-navigation (and its dependencies) installed into the React Native test fixtures to 6.x because v7.x fails to build on React Native 0.71 Android.
> Pin react-navigation to v6.x in React Native test fixtures

- packages/platforms/react-native/lib/NativeBugsnagPerformance.ts
Replace the use of optional properties with `| undefined` types in Turbo Module type definitions. 
This is in line with the type mappings in the React Native docs and is more representative of the native types to which they map.
> Avoid optional properties in Turbo Module spec

- .buildkite/browser-pipeline.full.yml
- test/browser/features/fixtures/packages/rollup.config.mjs
- test/browser/features/resource-load-spans.feature
Fixes the "full build" CI pipeline following the change to use `--https`:
- Disable `--https` for the browser mobile tests. Whilst they do work on android they do not on iOS but it doesn't seem worth splitting the build step so just disable for all
- Fix the CDN build to take into account the new document server path
> fix CI full pipeline

- packages/platforms/react-native/android/src/main/java/com/bugsnag/android/performance/NativeBugsnagPerformanceImpl.java
- packages/platforms/react-native/android/src/main/java/com/bugsnag/android/performance/ReactNativeSpanContext.java
- packages/platforms/react-native/android/src/newarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
- packages/platforms/react-native/android/src/oldarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
- packages/platforms/react-native/lib/NativeBugsnagPerformance.ts
Add support for starting native spans on Android
Added a new Turbo Module method called `startNativeSpan` which creates a span in the Android Performance SDK and returns a JS representation of the native Android span to JS.
The Turbo Module method accepts a limited set of span options (`startTime` and `parentContext`) as native spans should always be first class and should never become the current context in the native SDK.
Tested manually as this is not yet being used
> feat(react-native): support for starting native spans on android

- .github/workflows/signing.yml
Adds a workflow to upload signatures for the assets in a release.
> Add workflow to sign release assets

- .buildkite/block.full.yml
- .buildkite/browser-pipeline.full.yml
- .buildkite/browser-pipeline.yml
- .buildkite/pipeline.full.yml
- .buildkite/pipeline.yml
- .buildkite/react-native-navigation-pipeline.full.yml
- .buildkite/react-native-navigation-pipeline.yml
- .buildkite/react-native-pipeline.full.yml
- .buildkite/react-native-pipeline.yml
General tidy-up of the Buildkite pipeline to:
- Ensure all steps have an adequate but not excessive timeout
- Agent queues are explicitly stated in each file (even if a default is used)
- Generic `macos` queue is used instead of specific macOS versions where possible
Covered by a full CI run.
> Buildkite pipeline tidy-up

- packages/core/lib/core.ts
- packages/core/lib/plugin.ts
- packages/core/tests/core.test.ts
- packages/platforms/browser/tests/on-settle/index.test.ts
- packages/test-utilities/lib/create-test-client.ts
Add a new `appState` property and `setAppState` to the core client.
Add unit test to test `setAppState` 
Update `createTestClient` default options
> Implement current state enum in client

- packages/platforms/react-native/android/src/main/java/com/bugsnag/android/performance/NativeBugsnagPerformanceImpl.java
- packages/platforms/react-native/android/src/main/java/com/bugsnag/android/performance/ReactNativeSpanAttributes.java
- packages/platforms/react-native/android/src/newarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
- packages/platforms/react-native/android/src/oldarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
- packages/platforms/react-native/lib/NativeBugsnagPerformance.ts
Update the Android Turbo Module to support ending native spans, including support for marking a native span's end time independently of processing the span.
Added two new Turbo Module methods:
- `markNativeSpanEndTime` - sets the end time on a span without sending the span to be processed by the native SDK. This allows us to mark the end time and get an accurate end metrics snapshot in situations where the end time is overridden, e.g. navigation plugins.
- `endNativeSpan` - fully ends a native span and sends it for processing by the native SDK, translating the final JS attributes into native span attributes.
The Turbo Module now stores references to native spans in a `HashMap` when they are started so that they can be retrieved and ended later. The reference is removed when the span is …
> feat(react-native): support ending native android spans

- packages/platforms/react-native/ios/BugsnagPerformanceSpan.h
- packages/platforms/react-native/ios/BugsnagReactNativePerformance.mm
- packages/platforms/react-native/ios/BugsnagReactNativePerformance.xcodeproj/project.pbxproj
- packages/platforms/react-native/ios/ReactNativeSpanAttributes.h
- packages/platforms/react-native/ios/ReactNativeSpanAttributes.mm
Update the iOS Turbo Module to support ending native spans, including support for marking a native span's end time independently of processing the span.
This is the iOS equivalent implementation of https://github.com/bugsnag/bugsnag-js-performance/pull/548 (Android)
Added iOS implementations for the following Turbo Module methods:
- `markNativeSpanEndTime` - sets the end time on a span without sending the span to be processed by the native SDK. This allows us to mark the end time and get an accurate end metrics snapshot in situations where the end time is overridden, e.g. navigation plugins.
- `endNativeSpan` - fully ends a native span and sends it for processing by the native SDK, translating the final JS attributes into native span attributes.
The Turbo Module now stores references to …
> feat(react-native): support ending native ios spans

- .github/dependabot.yml
- .github/workflows/compare-pr-stats.yml
- .github/workflows/node-ci.yml
- .github/workflows/record-pr-stats.yml
- .github/workflows/signing.yml
Bumps the soon-to-be-deprecated `upload-artifact` as well as pinning all the dependencies and using dependabot config to check for updates weekly.
> bump and pin GitHub Action dependencies

- packages/platforms/react-native/lib/client.ts
- packages/platforms/react-native/lib/platform-extensions.tsx
- packages/platforms/react-native/tests/platform-extensions.test.ts
Update the `attach` platform extension to remove the need for monkey-patching in `client.ts` 
Previously the `attach` platform extension was implemented as a noop function that was then monkey-patched in `client.ts` - this was an ugly hack to allow us to call `start` from within the `attach` function.
Instead, we can convert the platform extensions to function declarations - this fixes the `this` binding so that `this` refers to the client object that's being extended - we still need to cast `this` to the correct type, but this means we can call other methods on the client without the need for monkey patching. 
Covered by existing tests
> React Native platform extensions improvements

- packages/platforms/react-native/__mocks__/react-native.ts
- packages/platforms/react-native/lib/NativeBugsnagPerformance.ts
- packages/platforms/react-native/lib/client.ts
- packages/platforms/react-native/lib/id-generator.ts
- packages/platforms/react-native/lib/native.ts
- packages/platforms/react-native/lib/persistence/file-native.ts
- packages/platforms/react-native/tests/id-generator.test.ts
- packages/platforms/react-native/tests/native.test.ts
- packages/platforms/react-native/tests/resource-attributes-source.test.ts
Remove check for null in turbomodules loading.
Added a default proxy for situations where neither new nor old turbomodule can be loaded.
Changed unit tests for id generation - by default tests always fallback to JS implementation because proxy's return value is empty. But no null check needed.
> Turbomodule changed to never be null, default object used instead

- packages/platforms/react-native/__mocks__/react-native.ts
- packages/platforms/react-native/android/src/main/java/com/bugsnag/android/performance/NativeBugsnagPerformanceImpl.java
- packages/platforms/react-native/android/src/newarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
- packages/platforms/react-native/android/src/oldarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
- packages/platforms/react-native/ios/BugsnagReactNativePerformance.mm
- packages/platforms/react-native/lib/NativeBugsnagPerformance.ts
- packages/platforms/react-native/lib/platform-extensions.tsx
- packages/platforms/react-native/tests/client.test.ts
The Turbo Module holds references to the native spans it creates so that they can be retrieved and ended later. This has the potential for memory leaks if for some reason the spans are never ended in JS. 
This PR tries to mitigate this by periodically discarding any native spans that have been open for a long time (> 1 hour)
When attach is called in JS, the Turbo Module schedules a task to run every hour and discard any spans with a start time more than 1 hour in the past.
Tested manually as it's not possible to automate
> Periodically clean up native spans that are open for > 1 hour

- .buildkite/react-native-pipeline.full.yml
- bin/generate-react-native-fixture
- packages/platforms/react-native/android/build.gradle
- packages/platforms/react-native/android/src/main/java/com/bugsnag/android/performance/NativeBugsnagPerformanceImpl.java
- test/react-native/features/fixtures/scenario-launcher/android/build.gradle
Add native integration tests for older RN versions to the full CI pipeline, and update dependencies to use the publicly released versions of Android and Cocoa Performance.
This also required some code changes to the Android native module to support building in a RN 0.64 project.
- Added native integration tests to the full Android/iOS pipelines
- Updated the Android Performance compile dependency in `@bugsnag/react-native-performance` to the released version.
- Updated the test fixture generation script:
- Test fixture now installs the publicly released Android and Cocoa Performance instead of pulling these from GH.
- Bumped the min ios version for test fixtures below RN 0.73 (required for Cocoa Performance)
- Updated the Android native module to remove var and lambda functions (these …
> Add Native integration tests to full CI pipeline

- packages/platforms/react-native/lib/client.ts
- packages/platforms/react-native/lib/platform-extensions.tsx
- packages/platforms/react-native/lib/span-factory.ts
- packages/platforms/react-native/tests/client.test.ts
- packages/platforms/react-native/tests/platform-extensions.test.ts
- packages/platforms/react-native/tests/span-factory.test.ts
Currently when `attach` is called, if the JS SDK cannot communicate with the native Android/Cocoa SDK, either because it hasn't been installed, is incompatible, or hasn't been started, we log a warning and noop.
But that means we don't call `start` on the JS client - so the native span delegation will be disabled, but customers can still then create JS spans, and these will just accumulate in memory (as they would if you start a span before `start` is called).
Instead, we should fail loudly and throw an error as this means something is misconfigured and the SDK cannot be started.
Also removed some unnecessary null checks around `NativeBugsnagPerformance` (since we now have a JS fallback)
> Throw errors from attach when native SDK is not available

- docker-compose.yml
Updates CI to forward browser and React Native e2e test data to separate dashboard projects as some dashboard features are only enabled for specific project types
Currently this is controlled by setting `MAZE_REPEATER_API_KEY` on the buildkite schedule, which applies to both sets of tests. When this PR is merged this will be split into two separate variables in the schedule, `MAZE_REPEATER_API_KEY_JS` and `MAZE_REPEATER_API_KEY_RN`.
These are then passed through to the respective containers as `MAZE_REPEATER_API_KEY` in `docker-compose.yml`.
Tested manually by triggering a manual build with env vars set
> Proxy browser and RN test data to separate dashboard projects

- .github/workflows/compare-pr-stats.yml
- .github/workflows/node-ci.yml
- .github/workflows/record-pr-stats.yml
- .github/workflows/signing.yml
Ensure github actions have appropriate for each job
> Update permissions for github actions

- test/browser/features/angular.feature
- test/browser/features/fixtures/packages/react-router/rollup.config.mjs
- test/browser/features/fixtures/packages/react/rollup.config.mjs
- test/browser/features/fixtures/packages/react/src/index.jsx
Update cdn rollup configuration causing test fixture build failures
Skip broken angular tests (ticket raised to resolve this)
> Fix cdn configuration for test fixture

- test/react-native/features/steps/react-native-steps.rb
Do not use Maze.driver directly, so that any Appium session failures are reported.
Covered by CI.
> Do not use Maze.driver directly

- .buildkite/browser-pipeline.yml
- docker-compose.yml
- dockerfiles/Dockerfile.browser-feature-builder
- test/browser/features/navigation-changes.feature
Stop using the legacy Selenium driver, it's not needed.
As part of working this change, I discovered a bug in Maze Runner that meant we hadn't be running on Edge 80.  Having fixed that, I discovered that the navigation scenarios fail - these are now skipped pending further investigation.
Covered by unblocking all browser tests on CI.
> Stop using legacy Selenium driver 

- bin/generate-react-native-fixture
- test/react-native/features/fixtures/scenario-launcher/android/build.gradle
- test/react-native/features/fixtures/scenario-launcher/android/src/main/java/com/bugsnag/reactnative/scenariolauncher/ScenarioLauncherImpl.java
- test/react-native/features/fixtures/scenario-launcher/android/src/newarch/java/com/bugsnag/reactnative/scenariolauncher/ScenarioLauncher.java
- test/react-native/features/fixtures/scenario-launcher/android/src/oldarch/java/com/bugsnag/reactnative/scenariolauncher/ScenarioLauncher.java
- test/react-native/features/fixtures/scenario-launcher/ios/ScenarioLauncher.h
- test/react-native/features/fixtures/scenario-launcher/ios/ScenarioLauncher.mm
- test/react-native/features/fixtures/scenario-launcher/lib/NativeScenarioLauncher.ts
- test/react-native/features/fixtures/scenario-launcher/lib/Persistence.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/RemoteParentContextJSScenario.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/RemoteParentContextNativeScenario.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/index.js
- test/react-native/features/remote-parent-context.feature
Add e2e tests for RemoteParentContext
These tests cover encoding and decoding of traceparent strings for both the React Native and native Android and Cocoa SDKs, utilizing the exiting native integration fixture to test the cross-layer functionality
Covered by CI
> RemoteParentContext e2e tests

- bin/release.sh
Fixes an issue with the release script where the `lerna version` command was causing unwanted changes to the `package-lock.json`
the `lerna version` command runs npm install with `legacy_peer_deps` internally, which result sin changes to the lockfile, so we explicitly set this to false to work around the issue.
> Fix release script

- test/react-native/features/steps/react-native-steps.rb
Removes an undefined variable from the Ruby test code - this was causing test failures unnecessarily, the line is only trying to log a warning message.
Verified by review only.
> Remove undefined variable

- .buildkite/scripts/packages.json
- bin/generate-expo-fixture
- bin/generate-react-native-fixture
- packages/platforms/react-native/android/build.gradle
- packages/plugin-react-native-span-access/android/build.gradle
- packages/plugin-react-native-span-access/android/src/main/AndroidManifest.xml
- packages/plugin-react-native-span-access/android/src/main/java/com/bugsnag/reactnative/performance/nativespans/BugsnagNativeSpansPlugin.java
- packages/plugin-react-native-span-access/android/src/newarch/java/com/bugsnag/reactnative/performance/nativespans/BugsnagNativeSpansModule.java
- packages/plugin-react-native-span-access/ios/BugsnagNativeSpans.xcodeproj/project.pbxproj
- test/react-native/features/fixtures/scenario-launcher/android/build.gradle
Switch the Android Performance dependencies to the latest version (1.16.0), reinstate skipped tests and fix last remaining compatibility issues in plugin-react-native-span-access for older versions of React Native
Covered by CI
> Bump Android Performance dependencies to 1.16.0 and fix compatibility issues

- docker-compose.yml
Allow e2e test requests to be forwarded to InsightHub.
With these in place we can set API keys in our secrets bucket and have e2e test requests forwarded to InsightHub for testing purposes.
Covered by CI.
> Allow e2e test requests to be forwarded to InsightHub

- test/browser/features/svelte-kit.feature
Skip testing on platforms not supported by SvelteKit due to ES2020 requirements
> Skip SvelteKit tests on Safari 13

- .buildkite/scripts/pipeline-trigger.js
- .gitignore
Only run full builds on next when FULL_SCHEDULED_BUILD is set.
We run a full build every morning, so there's no need to run a full build on `next` after every PR merge during the day.
Branched off of this and created a build manually with the variable set.  I'll also check that a full build doesn't occur after merging this.
> Only run full builds on next when FULL_SCHEDULED_BUILD is set.

- CHANGELOG.md
- packages/platforms/react-native/lib/backgrounding-listener.ts
- packages/platforms/react-native/tests/backgrounding-listener.test.ts
- test/react-native/features/manual-spans.feature
Add a short grace period (700ms) if the SDK is started in a reported background state, before we consider the app to be "in background".
If an app reports a background state during startup and then the AppState becomes "active" we would discard the `AppStart` spans. This was happening most notably on our Android 12 Old Arch tests, but is likely a broader problem.
By always considering an app as being `"in-foreground"` to start with, we don't emit a "change" event if the app is about to appear. Apps now always behave as though they are "probably" launching in the foreground.
Updated the unit tests, and the "Android 12 Old Arch" end-to-end tests now pass more reliably.
> ReactNative: handle background -> foreground startups

- packages/plugin-react-native-span-access/android/src/main/java/com/bugsnag/reactnative/performance/nativespans/BugsnagNativeSpans.java
- packages/plugin-react-native-span-access/android/src/newarch/java/com/bugsnag/reactnative/performance/nativespans/BugsnagNativeSpansModule.java
- packages/plugin-react-native-span-access/android/src/oldarch/java/com/bugsnag/reactnative/performance/nativespans/BugsnagNativeSpansModule.java
- packages/plugin-react-native-span-access/ios/BugsnagJavascriptSpanControl.h
- packages/plugin-react-native-span-access/ios/BugsnagJavascriptSpanControl.mm
- packages/plugin-react-native-span-access/ios/BugsnagJavascriptSpansPlugin+Private.h
- packages/plugin-react-native-span-access/ios/BugsnagJavascriptSpansPlugin.mm
- packages/plugin-react-native-span-access/ios/BugsnagNativeSpans.mm
- packages/plugin-react-native-span-access/lib/NativeBugsnagNativeSpans.ts
- packages/plugin-react-native-span-access/lib/javascript-spans-plugin.ts
- packages/plugin-react-native-span-access/tests/javascript-spans-plugin.test.ts
- packages/test-utilities/__mocks__/react-native.ts
- test/react-native/features/fixtures/scenario-launcher/android/src/main/java/com/bugsnag/reactnative/scenariolauncher/ScenarioLauncherImpl.java
- test/react-native/features/fixtures/scenario-launcher/android/src/newarch/java/com/bugsnag/reactnative/scenariolauncher/ScenarioLauncher.java
- test/react-native/features/fixtures/scenario-launcher/android/src/oldarch/java/com/bugsnag/reactnative/scenariolauncher/ScenarioLauncher.java
- test/react-native/features/fixtures/scenario-launcher/ios/ScenarioLauncher.mm
- test/react-native/features/fixtures/scenario-launcher/lib/NativeScenarioLauncher.ts
- test/react-native/features/fixtures/scenario-launcher/scenarios/native-integration/JavascriptSpansContextScenario.js
- test/react-native/features/fixtures/scenario-launcher/scenarios/native-integration/index.js
- test/react-native/features/react-native-span-access.feature
Introduces a new `retrieveSpanContext` method on `BugsnagJavascriptSpanControl` that allows retrieving the span context for a Javascript span to facilitate cross-layer span parentage.
Span contexts are returned asynchronously via a callback passed to `retrieveSpanContext`. JS span contexts are transmitted over the wire as traceparent strings which are then used to create a `BugsnagPerformanceRemoteSpanContext` object on the native side.
Added a new e2e test scenario
> Javascript span context retrieval for iOS

- CHANGELOG.md
- packages/platforms/react-native/ios/BugsnagReactNativePerformance.mm
When calling `startSpan` the `requestEntropy` function is called once to generate values for the span IDs. After the first 1000 spans the values are regenerated using the `requestEntropyAsync` function but the objc file has a typo which causes it to crash when called.
(see the original PR from @maxphillipsdev for more details: https://github.com/bugsnag/bugsnag-js-performance/pull/662)
Just fixed the typo in the argument name.
Tested manually
> Fix iOS crash from requestEntropyAsync

- .buildkite/expo-pipeline.full.yml
- .buildkite/expo-pipeline.yml
Move Expo build steps to macos-15 queue.
Xcode version is pinned to 16.2.0 where dictated by the version of Expo.
Covered by CI with both Expo arms triggered.
> Move Expo build steps to macos-15 queue

- packages/plugin-react-native-span-access/ios/BugsnagNativeSpansPlugin.mm
Improves the handling of span timoeut timers in `BugsnagNativeSpansPlugin`
- Ensure that span references and associated timers are removed when the tracked span is overwritten by a new span with the same name.
- Fixes a memory leak related to the usage of `NSTimer` for handling span timeouts in `BugsnagNativeSpansPlugin`
the `NSTimer` based span timeout timers were occasionally not firing for some tracked spans (network spans) that are not ended, due to run loop issues. This was causing memory leaks due to timeout timers not firing being removed. This PR switches to using GCD for span timeout timers, which avoids the issue and also has lower overheads
In addition, span timeout timers for a given span are now removed if a new span with the same name is started, avoiding holding references …
> Improve span timoeut handling in BugsnagNativeSpansPlugin

- CHANGELOG.md
- packages/core/lib/attributes.ts
- packages/core/lib/span.ts
- packages/core/tests/attributes.test.ts
- test/browser/features/custom-attributes.feature
- test/browser/features/fixtures/packages/custom-attributes/src/index.js
Previously calls to `setAttribute` with `null` or `undefined` values were ignored, so there was no way to remove span attributes. This PR updates the implementation so that calling `setAttribute` with a `null` or `undefined` attribute value clears the attribute from the span.
Updated the `SpanAttribute` type to accept null/undefined values and updated the `set` and `setCustom` methods to remove the attribute if the value is `null` or `undefined`
Updated the attribute unit tests and updated the maze runner scenario to verify that span attributes can now be removed.
> Calling setAttribute with null/undefined should clear the attribute

- packages/platforms/react-native/android/src/main/java/com/bugsnag/android/performance/NativeBugsnagPerformanceImpl.java
- packages/platforms/react-native/android/src/main/java/com/bugsnag/android/performance/ReactNativeAppStartPlugin.java
- packages/platforms/react-native/android/src/newarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
- packages/platforms/react-native/android/src/oldarch/java/com/bugsnag/android/performance/BugsnagReactNativePerformance.java
- packages/platforms/react-native/ios/BugsnagReactNativePerformance.mm
- packages/platforms/react-native/lib/NativeBugsnagPerformance.ts
- packages/platforms/react-native/lib/platform-extensions.tsx
- packages/platforms/react-native/lib/span-factory.ts
- packages/platforms/react-native/tests/span-factory.test.ts
- packages/test-utilities/__mocks__/react-native.ts
Introduces a new `ReactNativeAppStartPlugin` to support linking React Native App Start spans with their corresponding native view load. 
When the plugin is enabled, native view load traces will also include React Native app starts as child spans, and the view load span duration will cover the full time taken to load a React Native view from the native layer through to the React component being rendered.
The plugin uses span callbacks to track the start and end of view load spans. When a view load span is started, the plugin acquires a span condition with a relatively long (500ms) timeout.
When `attach` is called in the JS layer, the span condition is upgraded and the view load span context is returned to JS as a traceparent string, where it's used as the parent context for the subsequent …
> Native app starts plugin - Android

- .github/workflows/branch-sync.yml
Add GitHub action to sync changes from the `main` branch into `next`
The `AUTOMATION_TEAM_REVIEWERS` secret has also been added to the repository with the team @bugsnag/platforms-javascript-developers
This workflow will raise a PR whenever the main branch is updated, but will not recreate any additional PRs until after that one has been merged. allowing for updates to documentation, pushing additional tags, etc.
> Automate main -> next sync
